import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Navbar
    trips: 'Trips',
    shared_trips: 'Shared Trips',
    weather: 'Weather',
    tracker: 'Tracker',
    hotels: 'Bookings',
    budgets: 'Budgets',
    logged_in_as: 'Logged in as',
    profile: 'Profile',
    logout: 'Log Out',
    light_mode: 'Light Mode',
    dark_mode: 'Dark Mode',
    vault: 'Vault',
    community: 'Community',
    sign_in: 'Sign In',
    sign_up: 'Sign Up',
    go_to_dashboard: 'Go to Dashboard',
    get_started_free: "Get Started, It's Free",
    scroll_down_planner: 'Scroll down to open your planner',

    // Sky Radar / Tracker Page
    live_tracker: 'Live Aviation Radar',
    sky_radar: 'Sky Radar',
    live_api: 'Live',
    simulated_radar: 'Simulated Radar',
    tracked: 'Tracked',
    avg_speed: 'Avg Speed',
    avg_altitude: 'Avg Alt',
    search_placeholder: 'Search flight no. or country...',
    scanning_skies: 'Scanning skies for aircraft...',
    error_connecting: 'Unable to connect to flight server. Retrying...',
    try_again: 'Try again',
    next_update: 'Next update in',
    full_map: 'Full Map',
    show_radar_list: 'Show Radar List',
    en_route: 'EN ROUTE',
    origin: 'Origin',
    dest: 'Dest',
    heading: 'Heading',
    speed: 'Speed',
    altitude: 'Altitude',
    vrate: 'V-Rate',
    legend_title: 'Altitude Legend',
    legend_cruising: 'Cruising (> 30,000 ft)',
    legend_transition: 'Transition (10,000 - 30,000 ft)',
    legend_approach: 'Approach/Takeoff (< 10,000 ft)',
    legend_selected: 'Selected Aircraft',

    // Dashboard / Trips Page
    travel_hub: 'Personal Travel Hub',
    dashboard_title: 'My Trips Dashboard',
    dashboard_desc: 'Create and manage your customized itineraries.',
    create_new_trip: 'Create New Trip',
    recommended_trips: 'Recommended Pre-planned Trips',
    days_schedule: 'Days Custom Schedule',
    travelers: 'Travelers',
    my_saved_itineraries: 'My Saved Itineraries',
    loading_saved: 'Loading saved itineraries...',
    no_trips: 'No trips created yet',
    get_started: 'Get started by planning your first custom travel itinerary.',
    start_planning: 'Start Planning',
    day: 'day',
    days: 'days',
    budget_label: 'Budget',
    my_travel_journey: 'My Travel Journey',
    total_spend: 'Total Spend',
    regions_visited: 'Regions Visited',
    destinations_count: 'Destinations',
    destination_count: 'Destination',
    days_traveled: 'Days Traveled',
    days_unit: 'Days',
    travel_vibe: 'Travel Vibe',
    passport_stamp_collection: 'Passport Stamp Collection',
    passport_stamp_subtitle: 'Every trip planned adds a stamp to your digital passport.',
    stamps_label: 'Stamps',
    passport_empty_title: 'Your passport is empty',
    passport_empty_desc: 'Add your very first trip to start collecting visual destination stamps!',
    travel_milestones_title: 'Travel Milestones & Achievements',
    travel_milestones_subtitle: 'Explore more to unlock unique travel badges and track your achievements.',
    unlocked_label: 'Unlocked',
    locked_label: 'Locked',
    goal_label: 'Goal',
    daily_vibe: 'Daily Vibe',
    wanderlust_quotes: 'Wanderlust Quotes',
    grid_view: 'Grid View',
    map_view: 'Map View',
    ask_xplorism_ai: 'Ask Xplorism AI',
    online_assistant: 'Online Assistant',
    chat_welcome_title: 'Hi',
    chat_welcome_subtitle: 'I can create trip itineraries, look up weather/hotels, search destinations, and fetch preferences. Ask me anything!',
    chat_placeholder: 'Ask Xplorism AI...',
    regenerate_response: 'Regenerate response',
    clear_conversation: 'Clear conversation',
    thinking: 'Thinking...',
    login_to_chat: 'Login to Start Chatting',
    chat_guest_desc: 'Your AI travel guide is waiting to suggest customized itineraries, plan routes, and share current destination insights.',
    delete_chat_title: 'Delete Chat',
    delete_chat_confirm: 'Are you sure you want to permanently delete this chat? This action cannot be undone.',
    cancel_action: 'Cancel',
    delete_action: 'Delete',
    deleting_action: 'Deleting...',

    // Profile Page
    profile_title: 'User Profile',
    profile_desc: 'Manage your account settings, preferences, and view your stats.',
    back_to_dashboard: 'Back to Dashboard',
    joined: 'Joined',
    google_account_linked: 'Google Account Linked',
    log_out_session: 'Log Out of Session',
    travel_stats: 'Your Travel Stats',
    trips_planned: 'Trips Planned',
    total_itineraries: 'Total itineraries generated',
    favorites: 'Favorites',
    saved_locations: 'Saved locations & hotels',
    total_estimated_budget: 'Total Estimated Budget',
    total_spent: 'Combined value of planned trips',
    account_details: 'Account Details',
    full_name: 'Full Name',
    email_address: 'Email Address',
    change_password_label: 'Change Password',
    new_password_label: 'New Password',
    confirm_new_password_label: 'Confirm New Password',
    security_checklist: 'Security Checklist',
    travel_preferences_title: 'Travel Preferences',
    preferred_style: 'Preferred Travel Style',
    preferred_currency: 'Preferred Currency',
    email_notifications: 'Email Notifications',
    recommendations_desc: 'Recommendations and trip reminders',
    weekly_digest: 'Weekly Digest',
    curated_news_desc: 'Curated newsletters and travel deals',
    favorite_themes: 'Favorite Travel Themes',
    save_preferences: 'Save Preferences',
    save_changes: 'Save Changes',

    // Travel Styles Options
    style_adventure: 'Adventure & Exploring',
    style_leisure: 'Relaxation & Leisure',
    style_balanced: 'Balanced Mix',
    style_budget: 'Budget Backpacking',
    style_culinary: 'Culinary & Culture',

    // Weather Page
    climate_radar: 'Climate & Atmosphere',
    global_weather_forecast: 'Global Weather Forecast',
    weather_desc: 'Check real-time climates before booking your next journey.',
    search_city_placeholder: 'Search city, e.g. New York, London, Tokyo...',
    gathering_forecasts: 'Gathering local atmospheric forecasts...',
    feels_like: 'Feels Like',
    humidity_label: 'Humidity',
    wind_speed_label: 'Wind Speed',
    extended_outlook: 'Extended 7-Day Outlook',
    today: 'Today',
    discover_climates: 'Discover Global Climates',
    discover_climates_desc: 'Enter any city in the search bar above to map its atmospheric conditions and retrieve 7-day weather forecasts.',
    powered_by: 'Climate data powered by Open-Meteo.',

    // Weather Codes Options
    weather_clear_sky: 'Clear Sky',
    weather_mainly_clear: 'Mainly Clear',
    weather_partly_cloudy: 'Partly Cloudy',
    weather_overcast: 'Overcast',
    weather_foggy: 'Foggy',
    weather_rime_fog: 'Depositing Rime Fog',
    weather_light_drizzle: 'Light Drizzle',
    weather_moderate_drizzle: 'Moderate Drizzle',
    weather_dense_drizzle: 'Dense Drizzle',
    weather_slight_rain: 'Slight Rain',
    weather_moderate_rain: 'Moderate Rain',
    weather_heavy_rain: 'Heavy Rain',
    weather_slight_snow: 'Slight Snowfall',
    weather_moderate_snow: 'Moderate Snowfall',
    weather_heavy_snow: 'Heavy Snowfall',
    weather_slight_showers: 'Slight Rain Showers',
    weather_moderate_showers: 'Moderate Rain Showers',
    weather_violent_showers: 'Violent Rain Showers',
    weather_thunderstorm: 'Thunderstorm',
    weather_thunder_hail: 'Thunderstorm with Hail',
    weather_heavy_thunder: 'Heavy Thunderstorm',

    // Budgets List Page
    financial_overview: 'Financial Overview',
    my_saved_budgets: 'My Saved Budgets',
    budgets_desc: 'Monitor, track expenses, and manage budgets across all your saved itineraries.',
    aggregating_budgets: 'Aggregating budget calculations...',
    no_budgets: 'No itineraries budget logged',
    no_budgets_desc: 'Create and save a custom trip itinerary first to track real-time budgets and log expenses.',
    budget_limit: 'Limit',
    budget_spent: 'Spent',
    budget_utilization: 'Utilization',
    allocation_breakdown: 'Allocation Breakdown',
    edit_log_expenses: 'Edit & Log Expenses',

    // Categories Options
    category_accommodation: 'Accommodation',
    category_food_dining: 'Food & Dining',
    category_activities_tours: 'Activities & Tours',
    category_transportation: 'Transportation',
    category_shopping: 'Shopping',
    category_miscellaneous: 'Miscellaneous',

    // Budget Details Page
    budget_tracker: 'Budget Tracker',
    date_schedule: 'Date Schedule',
    traveler: 'Traveler',
    starting_budget: 'Starting Budget',
    calculating_breakdowns: 'Calculating planned breakdowns...',
    no_budget_data: 'No budget data available',
    no_budget_data_desc: "We couldn't compute budget trackers for this itinerary.",
    budget_planned: 'Planned',
    tracked_expenses_desc: 'Real-time tracked expenses',
    remaining_funds: 'Remaining',
    leftover_funds: 'Leftover funds',
    utilization_progress: 'Budget Utilization Progress',
    utilization_progress_desc: 'Shows current spend relative to total budget limit',
    add_new_expense: 'Log New Expense',
    category_label: 'Category',
    item_name_label: 'Item Name',
    date_label: 'Date',
    notes_label: 'Notes (optional)',
    planned_cost: 'Planned Amount',
    actual_spent: 'Actual Spent *',
    actions: 'Actions',
    no_expenses_logged: 'No actual expenses logged yet.',
    add_first_expense_desc: 'Click Add New Expense to start logging real-time costs.',
    item: 'item',
    items: 'items',
    of: 'of',
    save_expense: 'Save Expense',
    expense_history: 'Expense History',
    item_placeholder: 'e.g. Dinner at Bistro',
    notes_placeholder: 'Any additional details',
    cancel: 'Cancel',

    // Toast Notifications
    toast_trip_not_found: 'Trip not found',
    toast_load_trip_fail: 'Failed to load trip details.',
    toast_load_budget_fail: 'Failed to load budget details.',
    toast_fill_fields: 'Please fill in amount and date.',
    toast_expense_added: 'Expense added successfully!',
    toast_add_expense_fail: 'Failed to add expense.',
    toast_expense_updated: 'Expense updated successfully!',
    toast_update_expense_fail: 'Failed to update expense.',
    toast_expense_deleted: 'Expense deleted.',
    toast_delete_expense_fail: 'Failed to delete expense.',
    toast_load_itineraries_fail: 'Failed to load saved itineraries.',
    toast_save_trip_success: 'Pre-planned itinerary saved to your trips!',
    toast_save_trip_fail: 'Failed to save trip.',

    // Vault Page
    secure_storage: 'Encrypted Storage',
    vault_title: 'Document Vault',
    vault_subtitle: 'Securely store and manage your essential travel documents.',
    add_document: 'Add Document',
    expiry_warning: 'Expires soon!',
    expired: 'Expired!',
    passport: 'Passport',
    visa: 'Visa',
    ticket: 'Ticket',
    hotel_voucher: 'Hotel Voucher',
    insurance: 'Insurance',
    other: 'Other',
    doc_number: 'Document Number',
    expiry_date: 'Expiry Date',
    notes: 'Notes / Details',
    file_upload: 'Upload File',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    download: 'Download',
    confirm_delete: 'Are you sure you want to delete this document?',
    no_documents: 'No documents stored in your vault. Start by adding one!',
    // Community Feed Page
    community_feed: 'Explorers Social Feed',
    community_subtitle: 'Share logs, highlight moments, and interact with co-travelers from all over the world.',
    share_experience: 'Share Experience',
    search_posts_placeholder: 'Search posts by tags, user, or keywords...',
    no_stories_title: 'No stories shared yet',
    no_stories_desc: 'Be the first traveler to write a log and post pictures about your adventures!',
    start_writing: 'Start Writing',
    loading_social_logs: 'Loading social logs...',
    edit_experience: 'Edit Experience',
    share_an_experience: 'Share an Experience',
    experience_title: 'Experience Title',
    hashtags: 'Hashtags',
    type_tag_placeholder: 'Type tag & press Space/Enter',
    add_more: 'add more...',
    tell_story: 'Tell the story',
    tell_story_placeholder: 'Tell us what you experienced, cost-saving tips, or highlights...',
    add_photos_label: 'Add Highlight Photos (Max 5)',
    upload_trip_pictures: 'Upload Trip Pictures',
    upload_trip_pictures_sub: 'Supports multiple images (Max 5, 8MB each)',
    publishing: 'Publishing...',
    save_changes: 'Save Changes',
    post_experience: 'Post Experience',
    confirm_delete_post: 'Are you sure you want to delete this post?',
    likes: 'Likes',
    toast_post_deleted: 'Post deleted successfully',
    deleting: 'Deleting...',
    // Footer
    footer_slogan: 'Plan simpler, travel better. Experience the world with personalized itineraries, real-time updates, and collaborative planning tools.',
    features_title: 'Features',
    resources_title: 'Resources',
    stay_updated: 'Stay Updated',
    itinerary_builder: 'Itinerary Builder',
    interactive_map: 'Interactive Map',
    weather_forecast: 'Weather Forecast',
    budget_manager: 'Budget Manager',
    document_vault: 'Document Vault',
    travel_guides: 'Travel Guides',
    help_center: 'Help Center',
    community_feed_footer: 'Community Feed',
    terms_of_service: 'Terms of Service',
    privacy_policy: 'Privacy Policy',
    cookie_settings: 'Cookie Settings',
    newsletter_desc: 'Subscribe to our newsletter for the latest travel guides, tips, and feature updates.',
    email_placeholder: 'Enter your email',
    subscribe: 'Subscribe',
    all_rights_reserved: 'All rights reserved.'
  },
  es: {
    // Navbar
    trips: 'Viajes',
    shared_trips: 'Viajes Compartidos',
    weather: 'Clima',
    tracker: 'Rastreador',
    hotels: 'Hoteles',
    budgets: 'Presupuestos',
    logged_in_as: 'Conectado como',
    profile: 'Perfil',
    logout: 'Cerrar Sesión',
    light_mode: 'Modo Claro',
    dark_mode: 'Modo Oscuro',
    vault: 'Bóveda',
    community: 'Comunidad',
    sign_in: 'Iniciar Sesión',
    sign_up: 'Registrarse',
    go_to_dashboard: 'Ir al Panel',
    get_started_free: 'Comenzar, es Gratis',
    scroll_down_planner: 'Desplázate hacia abajo para abrir tu planificador',

    // Sky Radar / Tracker Page
    live_tracker: 'Radar de Aviación en Vivo',
    sky_radar: 'Radar del Cielo',
    live_api: 'En Vivo',
    simulated_radar: 'Radar Simulado',
    tracked: 'Rastreados',
    avg_speed: 'Vel. Promedio',
    avg_altitude: 'Alt. Promedio',
    search_placeholder: 'Buscar vuelo o país...',
    scanning_skies: 'Escaneando los cielos...',
    error_connecting: 'Error al conectar con el servidor de vuelo. Reintentando...',
    try_again: 'Intentar de nuevo',
    next_update: 'Próxima actualización en',
    full_map: 'Mapa Completo',
    show_radar_list: 'Mostrar Lista',
    en_route: 'EN RUTA',
    origin: 'Origen',
    dest: 'Destino',
    heading: 'Rumbo',
    speed: 'Velocidade',
    altitude: 'Altitud',
    vrate: 'Tasa Vertical',
    legend_title: 'Leyenda de Altitud',
    legend_cruising: 'Crucero (> 30,000 ft)',
    legend_transition: 'Transición (10k - 30k ft)',
    legend_approach: 'Despegue/Aterrizaje (< 10k ft)',
    legend_selected: 'Aeronave Seleccionada',

    // Dashboard / Trips Page
    travel_hub: 'Centro de viajes personal',
    dashboard_title: 'Panel de mis viajes',
    dashboard_desc: 'Crea y gestiona tus itinerarios personalizados.',
    create_new_trip: 'Crear Nuevo Viaje',
    recommended_trips: 'Viajes Recomendados Pre-planificados',
    days_schedule: 'Días de Horario Personalizado',
    travelers: 'Viajeros',
    my_saved_itineraries: 'Mis Itinerarios Guardados',
    loading_saved: 'Cargando itinerarios guardados...',
    no_trips: 'Aún no se han creado viajes',
    get_started: 'Comienza planeando tu primer itinerario de viaje personalizado.',
    start_planning: 'Iniciar Planificación',
    day: 'día',
    days: 'días',
    budget_label: 'Presupuesto',
    my_travel_journey: 'Mi Viaje de Exploración',
    total_spend: 'Gasto Total',
    regions_visited: 'Regiones Visitadas',
    destinations_count: 'Destinos',
    destination_count: 'Destino',
    days_traveled: 'Días Viajados',
    days_unit: 'Días',
    travel_vibe: 'Estilo de Viaje',
    passport_stamp_collection: 'Colección de Sellos de Pasaporte',
    passport_stamp_subtitle: 'Cada viaje planificado añade un sello a tu pasaporte digital.',
    stamps_label: 'Sellos',
    passport_empty_title: 'Tu pasaporte está vacío',
    passport_empty_desc: '¡Añade tu primer viaje para comenzar a coleccionar sellos de destinos!',
    travel_milestones_title: 'Hitos y Logros de Viaje',
    travel_milestones_subtitle: 'Explora más para desbloquear insignias de viaje y rastrear tus logros.',
    unlocked_label: 'Desbloqueado',
    locked_label: 'Bloqueado',
    goal_label: 'Meta',
    daily_vibe: 'Vibra Diaria',
    wanderlust_quotes: 'Citas de Pasión por Viajar',
    grid_view: 'Vista en Cuadrícula',
    map_view: 'Vista en Mapa',
    ask_xplorism_ai: 'Preguntar a Xplorism AI',
    online_assistant: 'Asistente en Línea',
    chat_welcome_title: '¡Hola',
    chat_welcome_subtitle: 'Puedo crear itinerarios, consultar clima/hoteles, buscar destinos y guardar preferencias. ¡Pregúntame lo que sea!',
    chat_placeholder: 'Pregunta a Xplorism AI...',
    regenerate_response: 'Regenerar respuesta',
    clear_conversation: 'Limpiar conversación',
    thinking: 'Pensando...',
    login_to_chat: 'Iniciar Sesión para Chatear',
    chat_guest_desc: 'Tu guía de viajes inteligente está listo para sugerirte itinerarios y rutas personalizadas.',
    delete_chat_title: 'Eliminar Chat',
    delete_chat_confirm: '¿Estás seguro de que deseas eliminar permanentemente este chat? Esta acción no se puede deshacer.',
    cancel_action: 'Cancelar',
    delete_action: 'Eliminar',
    deleting_action: 'Eliminando...',

    // Profile Page
    profile_title: 'Perfil de Usuario',
    profile_desc: 'Administra la configuración de tu cuenta, preferencias y estadísticas.',
    back_to_dashboard: 'Volver al Panel',
    joined: 'Registrado',
    google_account_linked: 'Cuenta de Google Vinculada',
    log_out_session: 'Cerrar Sesión',
    travel_stats: 'Estadísticas de Viajes',
    trips_planned: 'Viajes Planificados',
    total_itineraries: 'Itinerarios totales generados',
    favorites: 'Favoritos',
    saved_locations: 'Lugares y hoteles guardados',
    total_estimated_budget: 'Presupuesto Total Estimado',
    total_spent: 'Costo acumulado de viajes',
    account_details: 'Detalles de la Cuenta',
    full_name: 'Nombre Completo',
    email_address: 'Dirección de Correo',
    change_password_label: 'Cambiar Contraseña',
    new_password_label: 'Nueva Contraseña',
    confirm_new_password_label: 'Confirmar Nueva Contraseña',
    security_checklist: 'Lista de Seguridad',
    travel_preferences_title: 'Preferencias de Viaje',
    preferred_style: 'Estilo de Viaje Preferido',
    preferred_currency: 'Moneda Preferida',
    email_notifications: 'Notificaciones de Correo',
    recommendations_desc: 'Recomendaciones y recordatorios',
    weekly_digest: 'Resumen Semanal',
    curated_news_desc: 'Boletines y ofertas de viajes curados',
    favorite_themes: 'Temas de Viaje Favoritos',
    save_preferences: 'Guardar Preferencias',
    save_changes: 'Guardar Cambios',

    // Travel Styles Options
    style_adventure: 'Aventura y Exploración',
    style_leisure: 'Relajación y Ocio',
    style_balanced: 'Mezcla Equilibrada',
    style_budget: 'Mochilero Económico',
    style_culinary: 'Culinaria y Cultura',

    // Weather Page
    climate_radar: 'Clima y Atmósfera',
    global_weather_forecast: 'Pronóstico del Clima Global',
    weather_desc: 'Consulta los climas en tiempo real antes de reservar tu próximo viaje.',
    search_city_placeholder: 'Buscar ciudad, ej. Nueva York, Londres, Tokio...',
    gathering_forecasts: 'Obteniendo pronósticos atmosféricos locales...',
    feels_like: 'Sensación Térmica',
    humidity_label: 'Humedad',
    wind_speed_label: 'Vel. del Viento',
    extended_outlook: 'Pronóstico Extendido de 7 Días',
    today: 'Hoy',
    discover_climates: 'Descubrir Climas Globales',
    discover_climates_desc: 'Introduce cualquier ciudad en la barra de búsqueda superior para rastrear sus condiciones atmosféricas y obtener pronósticos de 7 días.',
    powered_by: 'Datos climáticos proporcionados por Open-Meteo.',

    // Weather Codes Options
    weather_clear_sky: 'Cielo Despejado',
    weather_mainly_clear: 'Mayormente Despejado',
    weather_partly_cloudy: 'Parcialmente Nublado',
    weather_overcast: 'Nublado',
    weather_foggy: 'Niebla',
    weather_rime_fog: 'Niebla Escarchada',
    weather_light_drizzle: 'Llovizna Ligera',
    weather_moderate_drizzle: 'Llovizna Moderada',
    weather_dense_drizzle: 'Llovizna Intensa',
    weather_slight_rain: 'Lluvia Ligera',
    weather_moderate_rain: 'Lluvia Moderada',
    weather_heavy_rain: 'Lluvia Fuerte',
    weather_slight_snow: 'Nevada Ligera',
    weather_moderate_snow: 'Nevada Moderada',
    weather_heavy_snow: 'Nevada Fuerte',
    weather_slight_showers: 'Chubascos Ligeros',
    weather_moderate_showers: 'Chubascos Moderados',
    weather_violent_showers: 'Chubascos Violentos',
    weather_thunderstorm: 'Tormenta Eléctrica',
    weather_thunder_hail: 'Tormenta con Granizo',
    weather_heavy_thunder: 'Tormenta Fuerte',

    // Budgets List Page
    financial_overview: 'Resumen Financiero',
    my_saved_budgets: 'Mis Presupuestos Guardados',
    budgets_desc: 'Supervisa, realiza el seguimiento de gastos y gestiona presupuestos en tus itinerarios.',
    aggregating_budgets: 'Agregando cálculos de presupuesto...',
    no_budgets: 'No se han registrado presupuestos',
    no_budgets_desc: 'Crea y guarda un itinerario primero para realizar el seguimiento de presupuestos y gastos.',
    budget_limit: 'Límite',
    budget_spent: 'Gastado',
    budget_utilization: 'Utilización',
    allocation_breakdown: 'Desglose de Asignación',
    edit_log_expenses: 'Editar y Registrar Gastos',

    // Categories Options
    category_accommodation: 'Alojamiento',
    category_food_dining: 'Comida',
    category_activities_tours: 'Actividades',
    category_transportation: 'Transporte',
    category_shopping: 'Compras',
    category_miscellaneous: 'Otros',

    // Budget Details Page
    budget_tracker: 'Seguimiento de Presupuesto',
    date_schedule: 'Calendario de Fechas',
    traveler: 'Viajero',
    starting_budget: 'Presupuesto Inicial',
    calculating_breakdowns: 'Calculando desgloses...',
    no_budget_data: 'No hay datos de presupuesto disponibles',
    no_budget_data_desc: "No pudimos calcular el presupuesto para este itinerario.",
    budget_planned: 'Planificado',
    tracked_expenses_desc: 'Gastos en tiempo real',
    remaining_funds: 'Restante',
    leftover_funds: 'Fondos sobrantes',
    utilization_progress: 'Progreso de Utilización del Presupuesto',
    utilization_progress_desc: 'Muestra el gasto actual en relación con el límite.',
    add_new_expense: 'Agregar Nuevo Gasto',
    category_label: 'Categoría',
    item_name_label: 'Nombre del Artículo',
    date_label: 'Fecha',
    notes_label: 'Notas (opcional)',
    planned_cost: 'Costo Planificado',
    actual_spent: 'Gastado Real *',
    actions: 'Acciones',
    no_expenses_logged: 'No se han registrado gastos aún.',
    add_first_expense_desc: 'Haz clic en Agregar Nuevo Gasto para comenzar a registrar costos.',
    item: 'artículo',
    items: 'artículos',
    of: 'de',
    save_expense: 'Guardar Gasto',
    expense_history: 'Historial de Gastos',
    item_placeholder: 'ej. Cena en Bistro',
    notes_placeholder: 'Detalles adicionales',
    cancel: 'Cancelar',

    // Toast Notifications
    toast_trip_not_found: 'Viaje no encontrado',
    toast_load_trip_fail: 'Error al cargar los detalles del viaje.',
    toast_load_budget_fail: 'Error al cargar los detalles del presupuesto.',
    toast_fill_fields: 'Por favor, introduce el importe y la fecha.',
    toast_expense_added: '¡Gasto agregado correctamente!',
    toast_add_expense_fail: 'Error al agregar el gasto.',
    toast_expense_updated: '¡Gasto actualizado correctamente!',
    toast_update_expense_fail: 'Error al actualizar el gasto.',
    toast_expense_deleted: 'Gasto eliminado.',
    toast_delete_expense_fail: 'Error al eliminar el gasto.',
    toast_load_itineraries_fail: 'Error al cargar los itinerarios guardados.',
    toast_save_trip_success: '¡Itinerario guardado correctamente!',
    toast_save_trip_fail: 'Error al guardar el viaje.',

    // Vault Page
    secure_storage: 'Almacenamiento Cifrado',
    vault_title: 'Bóveda de Documentos',
    vault_subtitle: 'Guarde y gestione de forma segura sus documentos de viaje.',
    add_document: 'Añadir Documento',
    expiry_warning: '¡Expira pronto!',
    expired: '¡Expirado!',
    passport: 'Pasaporte',
    visa: 'Visa',
    ticket: 'Boleto',
    hotel_voucher: 'Reserva de Hotel',
    insurance: 'Seguro de Viaje',
    other: 'Otro',
    doc_number: 'Número de Documento',
    expiry_date: 'Fecha de Expiración',
    notes: 'Notas / Detalles',
    file_upload: 'Cargar Archivo',
    save: 'Guardar',
    delete: 'Eliminar',
    edit: 'Editar',
    download: 'Descargar',
    confirm_delete: '¿Está seguro de que desea eliminar este documento?',
    no_documents: 'No hay documentos en su bóveda. ¡Comience por añadir uno!',
    // Community Feed Page
    community_feed: 'Feed Social de Exploradores',
    community_subtitle: 'Comparta registros, destaque momentos e interactúe con compañeros de viaje de todo el mundo.',
    share_experience: 'Compartir Experiencia',
    search_posts_placeholder: 'Buscar publicaciones por etiquetas, usuario o palabras clave...',
    no_stories_title: 'No hay historias compartidas aún',
    no_stories_desc: '¡Sé el primer viajero en escribir un registro y publicar fotos sobre tus aventuras!',
    start_writing: 'Comenzar a Escribir',
    loading_social_logs: 'Cargando publicaciones sociales...',
    edit_experience: 'Editar Experiencia',
    share_an_experience: 'Compartir una Experiencia',
    experience_title: 'Título de la Experiencia',
    hashtags: 'Hashtags',
    type_tag_placeholder: 'Escribe etiqueta y presiona Espacio/Intro',
    add_more: 'agregar más...',
    tell_story: 'Cuenta la historia',
    tell_story_placeholder: 'Cuéntanos qué experimentaste, consejos para ahorrar o lo más destacado...',
    add_photos_label: 'Agregar Fotos Destacadas (Máx. 5)',
    upload_trip_pictures: 'Subir Fotos del Viaje',
    upload_trip_pictures_sub: 'Soporta múltiples imágenes (Máx. 5, 8MB cada una)',
    publishing: 'Publicando...',
    save_changes: 'Guardar Cambios',
    post_experience: 'Publicar Experiencia',
    confirm_delete_post: '¿Estás seguro de que deseas eliminar esta publicación?',
    likes: 'Me gusta',
    toast_post_deleted: 'Publicación eliminada correctamente',
    deleting: 'Eliminando...',
    // Footer
    footer_slogan: 'Planifica más simple, viaja mejor. Experimenta el mundo con itinerarios personalizados, actualizaciones en tiempo real y herramientas de planificación colaborativa.',
    features_title: 'Funcionalidades',
    resources_title: 'Recursos',
    stay_updated: 'Mantente Actualizado',
    itinerary_builder: 'Creador de Itinerarios',
    interactive_map: 'Mapa Interactivo',
    weather_forecast: 'Pronóstico del Clima',
    budget_manager: 'Gestor de Presupuesto',
    document_vault: 'Bóveda de Documentos',
    travel_guides: 'Guías de Viaje',
    help_center: 'Centro de Ayuda',
    community_feed_footer: 'Feed de la Comunidad',
    terms_of_service: 'Condiciones de Servicio',
    privacy_policy: 'Política de Privacidad',
    cookie_settings: 'Configuración de Cookies',
    newsletter_desc: 'Suscríbete a nuestro boletín para recibir las últimas guías de viaje, consejos y actualizaciones de funciones.',
    email_placeholder: 'Introduce tu correo',
    subscribe: 'Suscribirse',
    all_rights_reserved: 'Todos los derechos reservados.'
  },
  fr: {
    // Navbar
    trips: 'Voyages',
    shared_trips: 'Voyages Partagés',
    weather: 'Météo',
    tracker: 'Radar',
    hotels: 'Hôtels',
    budgets: 'Budgets',
    logged_in_as: 'Connecté en tant que',
    profile: 'Profil',
    logout: 'Déconnexion',
    light_mode: 'Mode Clair',
    dark_mode: 'Mode Sombre',
    vault: 'Coffre',
    community: 'Communauté',
    sign_in: 'Se Connecter',
    sign_up: "S'inscrire",
    go_to_dashboard: 'Aller au Tableau de Bord',
    get_started_free: "Commencer, C'est Gratuit",
    scroll_down_planner: 'Faites défiler pour ouvrir votre planificateur',

    // Sky Radar / Tracker Page
    live_tracker: 'Radar d\'Aviation en Direct',
    sky_radar: 'Radar Aérien',
    live_api: 'En Direct',
    simulated_radar: 'Radar Simulé',
    tracked: 'Suivis',
    avg_speed: 'Vitesse Moy.',
    avg_altitude: 'Alt. Moyenne',
    search_placeholder: 'Rechercher un vol ou un pays...',
    scanning_skies: 'Scan du ciel en cours...',
    error_connecting: 'Impossible de se connecter au serveur. Re-tentative...',
    try_again: 'Réessayer',
    next_update: 'Mise à jour dans',
    full_map: 'Plein Écran',
    show_radar_list: 'Afficher la Liste',
    en_route: 'EN VOL',
    origin: 'Origine',
    dest: 'Destination',
    heading: 'Cap',
    speed: 'Vitesse',
    altitude: 'Altitude',
    vrate: 'Vitesse Vert.',
    legend_title: 'Légende des Altitudes',
    legend_cruising: 'Croisière (> 30 000 ft)',
    legend_transition: 'Transition (10k - 30k ft)',
    legend_approach: 'Approche/Décollage (< 10k ft)',
    legend_selected: 'Appareil Sélectionné',

    // Dashboard / Trips Page
    travel_hub: 'Centre de voyage personnel',
    dashboard_title: 'Mon Tableau de Bord de Voyages',
    dashboard_desc: 'Créez et gérez vos itinéraires personnalisés.',
    create_new_trip: 'Créer un Nouveau Voyage',
    recommended_trips: 'Voyages Recommandés Pré-planifiés',
    days_schedule: 'Jours de Programme Personnalisé',
    travelers: 'Voyageurs',
    my_saved_itineraries: 'Mes Itinéraires Enregistrés',
    loading_saved: 'Chargement des itinéraires enregistrés...',
    no_trips: 'Aucun voyage créé pour le moment',
    get_started: 'Commencez par planifier votre premier itinéraire de voyage personnalisé.',
    start_planning: 'Commencer la Planification',
    day: 'jour',
    days: 'jours',
    budget_label: 'Budget',
    my_travel_journey: 'Mon Parcours de Voyage',
    total_spend: 'Dépenses Totales',
    regions_visited: 'Régions Visitées',
    destinations_count: 'Destinations',
    destination_count: 'Destination',
    days_traveled: 'Jours de Voyage',
    days_unit: 'Jours',
    travel_vibe: 'Style de Voyage',
    passport_stamp_collection: 'Collection de Tampons de Passeport',
    passport_stamp_subtitle: 'Chaque voyage planifié ajoute un tampon à votre passeport numérique.',
    stamps_label: 'Tampons',
    passport_empty_title: 'Votre passeport est vide',
    passport_empty_desc: 'Ajoutez votre tout premier voyage pour commencer à collectionner des tampons !',
    travel_milestones_title: 'Étapes et Réussites de Voyage',
    travel_milestones_subtitle: 'Explorez davantage pour débloquer des badges et suivre vos exploits.',
    unlocked_label: 'Débloqué',
    locked_label: 'Verrouillé',
    goal_label: 'Objectif',
    daily_vibe: 'Ambiance du Jour',
    wanderlust_quotes: 'Citations de Voyage',
    grid_view: 'Vue Grille',
    map_view: 'Vue Carte',
    ask_xplorism_ai: 'Demander à Xplorism IA',
    online_assistant: 'Assistant en Ligne',
    chat_welcome_title: 'Bonjour',
    chat_welcome_subtitle: 'Je peux créer des itinéraires de voyage, vérifier la météo, rechercher des destinations et plus encore. Demandez-moi !',
    chat_placeholder: 'Demandez à Xplorism IA...',
    regenerate_response: 'Régénérer la réponse',
    clear_conversation: 'Effacer la conversation',
    thinking: 'Réflexion en cours...',
    login_to_chat: 'Se Connecter pour Discuter',
    chat_guest_desc: 'Votre guide de voyage IA est prêt à vous proposer des itinéraires personnalisés.',
    delete_chat_title: 'Supprimer la Discussion',
    delete_chat_confirm: 'Êtes-vous sûr de vouloir supprimer définitivement cette discussion ? Cette action est irréversible.',
    cancel_action: 'Annuler',
    delete_action: 'Supprimer',
    deleting_action: 'Suppression...',

    // Profile Page
    profile_title: 'Profil Utilisateur',
    profile_desc: 'Gérer les paramètres du compte, les préférences et les statistiques.',
    back_to_dashboard: 'Retour au Tableau de Bord',
    joined: 'Inscrit',
    google_account_linked: 'Compte Google Associé',
    log_out_session: 'Se Déconnecter de la Session',
    travel_stats: 'Statistiques de Voyage',
    trips_planned: 'Voyages Planifiés',
    total_itineraries: 'Itinéraires totaux générés',
    favorites: 'Favoris',
    saved_locations: 'Lieux & hôtels enregistrés',
    total_estimated_budget: 'Budget Total Estimé',
    total_spent: 'Coût cumulé des voyages',
    account_details: 'Détails du Compte',
    full_name: 'Nom Complet',
    email_address: 'Adresse E-mail',
    change_password_label: 'Changer le Mot de Passe',
    new_password_label: 'Nouveau Mot de Passe',
    confirm_new_password_label: 'Confirmar Nuevo Mot de Passe',
    security_checklist: 'Liste de Sécurité',
    travel_preferences_title: 'Préférences de Voyage',
    preferred_style: 'Style de Voyage Préféré',
    preferred_currency: 'Devise Préférée',
    email_notifications: 'Notifications par E-mail',
    recommendations_desc: 'Recommandations et rappels',
    weekly_digest: 'Résumé Hebdomadaire',
    curated_news_desc: 'Newsletters et offres de voyages',
    favorite_themes: 'Thèmes de Voyage Favoris',
    save_preferences: 'Enregistrer les Préférences',
    save_changes: 'Enregistrer les Modifications',

    // Travel Styles Options
    style_adventure: 'Aventure & Exploration',
    style_leisure: 'Détente & Loisirs',
    style_balanced: 'Mélange Équilibré',
    style_budget: 'Backpacking Économique',
    style_culinary: 'Culinaire & Culture',

    // Weather Page
    climate_radar: 'Climat & Atmosphère',
    global_weather_forecast: 'Prévisions Météo Globales',
    weather_desc: 'Consultez les climats en temps réel avant de réserver votre prochain voyage.',
    search_city_placeholder: 'Rechercher une ville, ex. New York, Londres, Voyage...',
    gathering_forecasts: 'Obtention des prévisions atmosphériques locales...',
    feels_like: 'Température Ressentie',
    humidity_label: 'Humidité',
    wind_speed_label: 'Vitesse du Vent',
    extended_outlook: 'Prévisions Étendues sur 7 Jours',
    today: 'Aujourd\'hui',
    discover_climates: 'Découvrir les Climats Globaux',
    discover_climates_desc: 'Entrez une ville dans la barre de recherche ci-dessus pour cartographier ses conditions atmosphériques.',
    powered_by: 'Données climatiques fournies par Open-Meteo.',

    // Weather Codes Options
    weather_clear_sky: 'Ciel Dégagé',
    weather_mainly_clear: 'Principalement Dégagé',
    weather_partly_cloudy: 'Partiellement Nuageux',
    weather_overcast: 'Couvert',
    weather_foggy: 'Brouillard',
    weather_rime_fog: 'Brouillard Givrant',
    weather_light_drizzle: 'Bruine Légère',
    weather_moderate_drizzle: 'Bruine Modérée',
    weather_dense_drizzle: 'Bruine Dense',
    weather_slight_rain: 'Pluie Légère',
    weather_moderate_rain: 'Pluie Modérée',
    weather_heavy_rain: 'Forte Pluie',
    weather_slight_snow: 'Faibles Chutes de Neige',
    weather_moderate_snow: 'Chutes de Neige Modérées',
    weather_heavy_snow: 'Fortes Chutes de Neige',
    weather_slight_showers: 'Faibles Averses de Pluie',
    weather_moderate_showers: 'Averses de Pluie Modérées',
    weather_violent_showers: 'Violentes Averses de Pluie',
    weather_thunderstorm: 'Orage',
    weather_thunder_hail: 'Orage avec Grêle',
    weather_heavy_thunder: 'Fort Orage',

    // Budgets List Page
    financial_overview: 'Aperçu Financier',
    my_saved_budgets: 'Mes Budgets Enregistrés',
    budgets_desc: 'Suivez les dépenses et gérez les budgets de vos itinéraires personnalisés.',
    aggregating_budgets: 'Agrégation des calculs budgétaires...',
    no_budgets: 'Aucun budget enregistré',
    no_budgets_desc: 'Créez d\'abord un itinéraire pour suivre les budgets et enregistrer vos dépenses.',
    budget_limit: 'Limite',
    budget_spent: 'Dépensé',
    budget_utilization: 'Utilisation',
    allocation_breakdown: 'Répartition des Dépenses',
    edit_log_expenses: 'Modifier & Enregistrer Dépenses',

    // Categories Options
    category_accommodation: 'Hébergement',
    category_food_dining: 'Nourriture',
    category_activities_tours: 'Activités',
    category_transportation: 'Transport',
    category_shopping: 'Achats',
    category_miscellaneous: 'Divers',

    // Budget Details Page
    budget_tracker: 'Suivi Budgétaire',
    date_schedule: 'Calendrier des Dates',
    traveler: 'Voyageur',
    starting_budget: 'Budget Initial',
    calculating_breakdowns: 'Calcul des répartitions...',
    no_budget_data: 'Aucune donnée budgétaire',
    no_budget_data_desc: "Calcul impossible pour ce voyage.",
    budget_planned: 'Planifié',
    tracked_expenses_desc: 'Dépenses suivies en temps réel',
    remaining_funds: 'Restant',
    leftover_funds: 'Fonds restants',
    utilization_progress: 'Progression de l\'Utilisation',
    utilization_progress_desc: 'Affiche les dépenses par rapport à la limite.',
    add_new_expense: 'Ajouter une Dépense',
    category_label: 'Catégorie',
    item_name_label: 'Nom de l\'Article',
    date_label: 'Date',
    notes_label: 'Notes (facultatif)',
    planned_cost: 'Coût Planifié',
    actual_spent: 'Dépensé Réel *',
    actions: 'Actions',
    no_expenses_logged: 'Aucune dépense enregistrée.',
    add_first_expense_desc: 'Cliquez sur Ajouter pour commencer.',
    item: 'article',
    items: 'articles',
    of: 'de',
    save_expense: 'Enregistrer',
    expense_history: 'Historique des Dépenses',
    item_placeholder: 'ex. Dîner au Bistro',
    notes_placeholder: 'Détails supplémentaires',
    cancel: 'Annuler',

    // Toast Notifications
    toast_trip_not_found: 'Voyage introuvable',
    toast_load_trip_fail: 'Impossible de charger les détails du voyage.',
    toast_load_budget_fail: 'Impossible de charger le budget.',
    toast_fill_fields: 'Veuillez saisir un montant et une date.',
    toast_expense_added: 'Dépense ajoutée avec succès !',
    toast_add_expense_fail: 'Échec de l\'ajout de la dépense.',
    toast_expense_updated: 'Dépense mise à jour avec succès !',
    toast_update_expense_fail: 'Échec de la mise à jour.',
    toast_expense_deleted: 'Dépense supprimée.',
    toast_delete_expense_fail: 'Échec de la suppression.',
    toast_load_itineraries_fail: 'Échec du chargement des itinéraires.',
    toast_save_trip_success: 'Itinéraire enregistré avec succès !',
    toast_save_trip_fail: 'Échec de l\'enregistrement du voyage.',

    // Vault Page
    secure_storage: 'Stockage Chiffré',
    vault_title: 'Coffre-fort',
    vault_subtitle: 'Stockez et gérez en toute sécurité vos documents de voyage.',
    add_document: 'Ajouter un Document',
    expiry_warning: 'Expire bientôt !',
    expired: 'Expiré !',
    passport: 'Passeport',
    visa: 'Visa',
    ticket: 'Billet',
    hotel_voucher: 'Bon d’hôtel',
    insurance: 'Assurance',
    other: 'Autre',
    doc_number: 'Numéro de Document',
    expiry_date: 'Date d’expiration',
    notes: 'Notes / Détails',
    file_upload: 'Télécharger le Fichier',
    save: 'Enregistrer',
    delete: 'Supprimer',
    edit: 'Modifier',
    download: 'Télécharger',
    confirm_delete: 'Voulez-vous vraiment supprimer ce document ?',
    no_documents: 'Aucun document stocké. Commencez par en ajouter un !',
    // Community Feed Page
    community_feed: 'Flux Social des Explorateurs',
    community_subtitle: 'Partagez des récits, marquez des moments et échangez avec des co-voyageurs du monde entier.',
    share_experience: 'Partager l\'Expérience',
    search_posts_placeholder: 'Rechercher des posts par tags, utilisateur ou mots-clés...',
    no_stories_title: 'Aucune histoire partagée pour le moment',
    no_stories_desc: 'Soyez le premier voyageur à écrire un récit et publier des photos de vos aventures !',
    start_writing: 'Commencer à Écrire',
    loading_social_logs: 'Chargement des publications sociales...',
    edit_experience: 'Modifier l\'Expérience',
    share_an_experience: 'Partager une Expérience',
    experience_title: 'Titre de l\'Expérience',
    hashtags: 'Hashtags',
    type_tag_placeholder: 'Tapez un tag et appuyez sur Espace/Entrée',
    add_more: 'ajouter...',
    tell_story: 'Raconter l\'histoire',
    tell_story_placeholder: 'Racontez-nous votre expérience, vos astuces budget ou vos moments forts...',
    add_photos_label: 'Ajouter des Photos (Max 5)',
    upload_trip_pictures: 'Téléverser des Photos de Voyage',
    upload_trip_pictures_sub: 'Prend en charge plusieurs images (Max 5, 8 Mo chacune)',
    publishing: 'Publication...',
    save_changes: 'Enregistrer les Modifications',
    post_experience: 'Publier l\'Expérience',
    confirm_delete_post: 'Êtes-vous sûr de vouloir supprimer cette publication ?',
    likes: 'J\'aime',
    toast_post_deleted: 'Publication supprimée avec succès',
    deleting: 'Suppression...',
    // Footer
    footer_slogan: 'Planifiez plus simplement, voyagez mieux. Découvrez le monde grâce à des itinéraires personnalisés, des mises à jour en temps réel et des outils de planification collaborative.',
    features_title: 'Fonctionnalités',
    resources_title: 'Ressources',
    stay_updated: 'Restez Informé',
    itinerary_builder: 'Générateur d\'Itinéraires',
    interactive_map: 'Carte Interactive',
    weather_forecast: 'Prévisions Météo',
    budget_manager: 'Gestionnaire de Budget',
    document_vault: 'Coffre-fort de Documents',
    travel_guides: 'Guides de Voyage',
    help_center: 'Centre d\'Aide',
    community_feed_footer: 'Flux Communautaire',
    terms_of_service: 'Conditions d\'Utilisation',
    privacy_policy: 'Politique de Confidentialité',
    cookie_settings: 'Paramètres des Cookies',
    newsletter_desc: 'Abonnez-vous à notre newsletter pour obtenir les derniers guides de voyage, conseils et nouveautés.',
    email_placeholder: 'Entrez votre e-mail',
    subscribe: 'S\'abonner',
    all_rights_reserved: 'Tous droits réservés.'
  },
  de: {
    // Navbar
    trips: 'Reisen',
    shared_trips: 'Gemeinsame Reisen',
    weather: 'Wetter',
    tracker: 'Flugradar',
    hotels: 'Hotels',
    budgets: 'Budgets',
    logged_in_as: 'Angemeldet als',
    profile: 'Profil',
    logout: 'Abmelden',
    light_mode: 'Heller Modus',
    dark_mode: 'Dunkler Modus',
    vault: 'Tresor',
    community: 'Gemeinschaft',
    sign_in: 'Anmelden',
    sign_up: 'Registrieren',
    go_to_dashboard: 'Zum Dashboard',
    get_started_free: 'Kostenlos starten',
    scroll_down_planner: 'Scrolle nach unten, um den Planer zu öffnen',

    // Sky Radar / Tracker Page
    live_tracker: 'Live-Luftfahrt-Radar',
    sky_radar: 'Himmelsradar',
    live_api: 'Live',
    simulated_radar: 'Simulierter Radar',
    tracked: 'Verfolgt',
    avg_speed: 'Durchschnittsgeschw.',
    avg_altitude: 'Durchschnittshöhe',
    search_placeholder: 'Suche Flugnr. oder Land...',
    scanning_skies: 'Scanne den Himmel...',
    error_connecting: 'Verbindung zum Server fehlgeschlagen. Erneuter Versuch...',
    try_again: 'Erneut versuchen',
    next_update: 'Nächstes Update in',
    full_map: 'Vollbildkarte',
    show_radar_list: 'Liste anzeigen',
    en_route: 'UNTERWEGS',
    origin: 'Abflug',
    dest: 'Ankunft',
    heading: 'Kurs',
    speed: 'Geschw.',
    altitude: 'Höhe',
    vrate: 'Steigrate',
    legend_title: 'Höhenlegende',
    legend_cruising: 'Reiseflug (> 30.000 ft)',
    legend_transition: 'Übergang (10k - 30k ft)',
    legend_approach: 'Steig-/Sinkflug (< 10k ft)',
    legend_selected: 'Ausgewähltes Flugzeug',

    // Dashboard / Trips Page
    travel_hub: 'Persönlicher Reise-Hub',
    dashboard_title: 'Meine Reisen Übersicht',
    dashboard_desc: 'Erstellen und verwalten Sie Ihre Reiserouten.',
    create_new_trip: 'Neue Reise erstellen',
    recommended_trips: 'Empfohlene vorgeplante Reisen',
    days_schedule: 'Tage individueller Zeitplan',
    travelers: 'Reisende',
    my_saved_itineraries: 'Meine gespeicherten Reiserouten',
    loading_saved: 'Lade gespeicherte Reiserouten...',
    no_trips: 'Noch keine Reisen erstellt',
    get_started: 'Beginnen Sie mit der Planung Ihrer ersten Reiseroute.',
    start_planning: 'Planung starten',
    day: 'Tag',
    days: 'Tage',
    budget_label: 'Budget',
    my_travel_journey: 'Meine Reiseerlebnisse',
    total_spend: 'Gesamtausgaben',
    regions_visited: 'Besuchte Regionen',
    destinations_count: 'Reiseziele',
    destination_count: 'Reiseziel',
    days_traveled: 'Gereiste Tage',
    days_unit: 'Tage',
    travel_vibe: 'Reisestil',
    passport_stamp_collection: 'Reisepass-Stempelsammlung',
    passport_stamp_subtitle: 'Jede geplante Reise fügt Ihrem digitalen Reisepass einen Stempel hinzu.',
    stamps_label: 'Stempel',
    passport_empty_title: 'Ihr Reisepass ist leer',
    passport_empty_desc: 'Fügen Sie Ihre allererste Reise hinzu, um Stempel zu sammeln!',
    travel_milestones_title: 'Reisemeilensteine & Erfolge',
    travel_milestones_subtitle: 'Erkunden Sie mehr, um Abzeichen freizuschalten und Erfolge zu verfolgen.',
    unlocked_label: 'Freigeschaltet',
    locked_label: 'Gesperrt',
    goal_label: 'Ziel',
    daily_vibe: 'Tagesstimmung',
    wanderlust_quotes: 'Fernweh-Zitate',
    grid_view: 'Rasteransicht',
    map_view: 'Kartenansicht',
    ask_xplorism_ai: 'Xplorism KI fragen',
    online_assistant: 'Online-Assistent',
    chat_welcome_title: 'Hallo',
    chat_welcome_subtitle: 'Ich kann Reiserouten erstellen, Wetter und Hotels abfragen und Reiseziele suchen. Frag mich alles!',
    chat_placeholder: 'Frag Xplorism KI...',
    regenerate_response: 'Antwort neu generieren',
    clear_conversation: 'Unterhaltung löschen',
    thinking: 'Nachdenken...',
    login_to_chat: 'Anmelden zum Chatten',
    chat_guest_desc: 'Dein intelligenter Reiseleiter wartet darauf, dir Reiserouten und Empfehlungen vorzuschlagen.',
    delete_chat_title: 'Chat Löschen',
    delete_chat_confirm: 'Möchtest du diesen Chat wirklich dauerhaft löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
    cancel_action: 'Abbrechen',
    delete_action: 'Löschen',
    deleting_action: 'Löschen...',

    // Profile Page
    profile_title: 'Benutzerprofil',
    profile_desc: 'Verwalten Sie Ihre Kontoeinstellungen, Präferenzen und Statistiken.',
    back_to_dashboard: 'Zurück zum Dashboard',
    joined: 'Mitglied seit',
    google_account_linked: 'Google-Konto verknüpft',
    log_out_session: 'Abmelden',
    travel_stats: 'Reisestatistiken',
    trips_planned: 'Geplante Reisen',
    total_itineraries: 'Gesamte Reiserouten',
    favorites: 'Favoriten',
    saved_locations: 'Gespeicherte Orte & Hotels',
    total_estimated_budget: 'Geschätztes Gesamtbudget',
    total_spent: 'Gesamtwert der geplanten Reisen',
    account_details: 'Kontodetails',
    full_name: 'Vollständiger Name',
    email_address: 'E-Mail-Adresse',
    change_password_label: 'Passwort ändern',
    new_password_label: 'Neues Passwort',
    confirm_new_password_label: 'Neues Passwort bestätigen',
    security_checklist: 'Sicherheitscheckliste',
    travel_preferences_title: 'Reisepräferenzen',
    preferred_style: 'Bevorzugter Reisestil',
    preferred_currency: 'Bevorzugte Währung',
    email_notifications: 'E-Mail-Benachrichtigungen',
    recommendations_desc: 'Empfehlungen und Reiseerinnerungen',
    weekly_digest: 'Wöchentliche Zusammenfassung',
    curated_news_desc: 'Kuratierte Newsletter und Reiseangebote',
    favorite_themes: 'Bevorzugte Reisethemen',
    save_preferences: 'Präferenzen speichern',
    save_changes: 'Änderungen speichern',

    // Travel Styles Options
    style_adventure: 'Abenteuer & Erkunden',
    style_leisure: 'Entspannung & Freizeit',
    style_balanced: 'Ausgewogene Mischung',
    style_budget: 'Günstiges Backpacking',
    style_culinary: 'Kulinarisch & Kultur',

    // Weather Page
    climate_radar: 'Klima & Atmosphäre',
    global_weather_forecast: 'Globale Wettervorhersage',
    weather_desc: 'Überprüfen Sie das Echtzeitwetter vor der Buchung Ihrer nächsten Reise.',
    search_city_placeholder: 'Stadt suchen, z. B. New York, London, Tokio...',
    gathering_forecasts: 'Rufe lokale Wettervorhersagen ab...',
    feels_like: 'Gefühlt wie',
    humidity_label: 'Feuchtigkeit',
    wind_speed_label: 'Windgeschw.',
    extended_outlook: 'Erweiterte 7-Tage-Prognose',
    today: 'Heute',
    discover_climates: 'Entdecken Sie das globale Wetter',
    discover_climates_desc: 'Geben Sie eine Stadt in die Suchleiste oben ein, um die atmosphärischen Bedingungen anzuzeigen.',
    powered_by: 'Wetterdaten bereitgestellt von Open-Meteo.',

    // Weather Codes Options
    weather_clear_sky: 'Klarer Himmel',
    weather_mainly_clear: 'Überwiegend Klar',
    weather_partly_cloudy: 'Teilweise Bewölkt',
    weather_overcast: 'Bedeckt',
    weather_foggy: 'Nebel',
    weather_rime_fog: 'Reifnebel',
    weather_light_drizzle: 'Leichter Sprühregen',
    weather_moderate_drizzle: 'Mäßiger Sprühregen',
    weather_dense_drizzle: 'Dichter Sprühregen',
    weather_slight_rain: 'Leichter Regen',
    weather_moderate_rain: 'Mäßiger Regen',
    weather_heavy_rain: 'Starker Regen',
    weather_slight_snow: 'Leichter Schneefall',
    weather_moderate_snow: 'Mäßiger Schneefall',
    weather_heavy_snow: 'Starker Schneefall',
    weather_slight_showers: 'Leichte Regenschauer',
    weather_moderate_showers: 'Mäßige Regenschauer',
    weather_violent_showers: 'Starke Regenschauer',
    weather_thunderstorm: 'Gewitter',
    weather_thunder_hail: 'Gewitter mit Hagel',
    weather_heavy_thunder: 'Starkes Gewitter',

    // Budgets List Page
    financial_overview: 'Finanzübersicht',
    my_saved_budgets: 'Meine Gespeicherten Budgets',
    budgets_desc: 'Überwachen, verfolgen Sie Ausgaben und verwalten Sie Budgets für Ihre Reiserouten.',
    aggregating_budgets: 'Berechnung der Budgets...',
    no_budgets: 'Keine Budgets protokolliert',
    no_budgets_desc: 'Erstellen Sie zuerst eine Reiseroute, um Budgets und Ausgaben zu verfolgen.',
    budget_limit: 'Limit',
    budget_spent: 'Ausgegeben',
    budget_utilization: 'Auslastung',
    allocation_breakdown: 'Aufteilungsübersicht',
    edit_log_expenses: 'Ausgaben bearbeiten & eintragen',

    // Categories Options
    category_accommodation: 'Unterkunft',
    category_food_dining: 'Essen',
    category_activities_tours: 'Aktivitäten',
    category_transportation: 'Transport',
    category_shopping: 'Einkaufen',
    category_miscellaneous: 'Sonstiges',

    // Budget Details Page
    budget_tracker: 'Budgetverfolgung',
    date_schedule: 'Terminplan',
    traveler: 'Reisender',
    starting_budget: 'Startbudget',
    calculating_breakdowns: 'Berechne Aufteilungen...',
    no_budget_data: 'Keine Budgetdaten verfügbar',
    no_budget_data_desc: "Berechnung nicht möglich für diese Reiseroute.",
    budget_planned: 'Geplant',
    tracked_expenses_desc: 'Echtzeit-Ausgaben',
    remaining_funds: 'Verbleibend',
    leftover_funds: 'Übriggebliebenes Budget',
    utilization_progress: 'Budgetauslastung',
    utilization_progress_desc: 'Zeigt aktuelle Ausgaben im Verhältnis zum Limit.',
    add_new_expense: 'Ausgabe Hinzufügen',
    category_label: 'Kategorie',
    item_name_label: 'Name',
    date_label: 'Datum',
    notes_label: 'Notizen (optional)',
    planned_cost: 'Geplante Kosten',
    actual_spent: 'Tatsächliche Kosten *',
    actions: 'Aktionen',
    no_expenses_logged: 'Keine Ausgaben protokolliert.',
    add_first_expense_desc: 'Klicken Sie auf Ausgabe Hinzufügen, um Ausgaben zu protokollieren.',
    item: 'Eintrag',
    items: 'Einträge',
    of: 'von',
    save_expense: 'Speichern',
    expense_history: 'Ausgabenverlauf',
    item_placeholder: 'z.B. Abendessen im Bistro',
    notes_placeholder: 'Zusätzliche Details',
    cancel: 'Abbrechen',

    // Toast Notifications
    toast_trip_not_found: 'Reise nicht gefunden',
    toast_load_trip_fail: 'Reiseroute konnte nicht geladen werden.',
    toast_load_budget_fail: 'Budget konnte nicht geladen werden.',
    toast_fill_fields: 'Bitte Betrag und Datum eintragen.',
    toast_expense_added: 'Ausgabe erfolgreich hinzugefügt!',
    toast_add_expense_fail: 'Ausgabe konnte nicht hinzugefügt werden.',
    toast_expense_updated: 'Ausgabe erfolgreich aktualisiert!',
    toast_update_expense_fail: 'Fehler beim Aktualisieren der Ausgabe.',
    toast_expense_deleted: 'Ausgabe gelöscht.',
    toast_delete_expense_fail: 'Fehler beim Löschen der Ausgabe.',
    toast_load_itineraries_fail: 'Laden der Reiserouten fehlgeschlagen.',
    toast_save_trip_success: 'Reiseroute erfolgreich gespeichert!',
    toast_save_trip_fail: 'Reise konnte nicht gespeichert werden.',

    // Vault Page
    secure_storage: 'Verschlüsselter Speicher',
    vault_title: 'Dokumententresor',
    vault_subtitle: 'Sichere Aufbewahrung und Verwaltung Ihrer Reisedokumente.',
    add_document: 'Dokument hinzufügen',
    expiry_warning: 'Läuft bald ab!',
    expired: 'Abgelaufen!',
    passport: 'Reisepass',
    visa: 'Visum',
    ticket: 'Ticket',
    hotel_voucher: 'Hotelgutschein',
    insurance: 'Versicherung',
    other: 'Anderes',
    doc_number: 'Dokumentennummer',
    expiry_date: 'Ablaufdatum',
    notes: 'Notizen / Details',
    file_upload: 'Datei hochladen',
    save: 'Speichern',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    download: 'Herunterladen',
    confirm_delete: 'Möchten Sie dieses Dokument wirklich löschen?',
    no_documents: 'Keine Dokumente im Tresor. Fügen Sie eines hinzu!',
    // Community Feed Page
    community_feed: 'Entdecker-Social-Feed',
    community_subtitle: 'Teilen Sie Reiseberichte, markieren Sie Erlebnisse und tauschen Sie sich mit Mitreisenden weltweit aus.',
    share_experience: 'Erfahrung Teilen',
    search_posts_placeholder: 'Beiträge nach Tags, Benutzern oder Schlüsselwörtern durchsuchen...',
    no_stories_title: 'Noch keine Erlebnisse geteilt',
    no_stories_desc: 'Schreiben Sie als Erster einen Bericht und posten Sie Bilder von Ihren Abenteuern!',
    start_writing: 'Jetzt Schreiben',
    loading_social_logs: 'Lade soziale Beiträge...',
    edit_experience: 'Erfahrung Bearbeiten',
    share_an_experience: 'Erfahrung Teilen',
    experience_title: 'Titel des Erlebnisses',
    hashtags: 'Hashtags',
    type_tag_placeholder: 'Tag eingeben & Leertaste/Eingabe drücken',
    add_more: 'mehr hinzufügen...',
    tell_story: 'Geschichte erzählen',
    tell_story_placeholder: 'Erzählen Sie uns von Ihren Erlebnissen, Spartipps oder Highlights...',
    add_photos_label: 'Highlight-Fotos hinzufügen (Max. 5)',
    upload_trip_pictures: 'Reisebilder hochladen',
    upload_trip_pictures_sub: 'Unterstützt mehrere Bilder (Max. 5, jeweils 8 MB)',
    publishing: 'Veröffentliche...',
    save_changes: 'Änderungen Speichern',
    post_experience: 'Erlebnis Posten',
    confirm_delete_post: 'Sind Sie sicher, dass Sie diesen Beitrag löschen möchten?',
    likes: 'Gefällt mir',
    toast_post_deleted: 'Beitrag erfolgreich gelöscht',
    deleting: 'Löschen...',
    // Footer
    footer_slogan: 'Einfacher planen, besser reisen. Erleben Sie die Welt mit personalisierten Reiserouten, Echtzeit-Updates und Tools zur gemeinsamen Planung.',
    features_title: 'Funktionen',
    resources_title: 'Ressourcen',
    stay_updated: 'Auf dem Laufenden bleiben',
    itinerary_builder: 'Routenplaner',
    interactive_map: 'Interaktive Karte',
    weather_forecast: 'Wettervorhersage',
    budget_manager: 'Budget-Manager',
    document_vault: 'Dokumententresor',
    travel_guides: 'Reiseführer',
    help_center: 'Hilfezentrum',
    community_feed_footer: 'Community-Feed',
    terms_of_service: 'Nutzungsbedingungen',
    privacy_policy: 'Datenschutzerklärung',
    cookie_settings: 'Cookie-Einstellungen',
    newsletter_desc: 'Abonnieren Sie unseren Newsletter für die neuesten Reiseführer, Tipps und Feature-Updates.',
    email_placeholder: 'E-Mail-Adresse eingeben',
    subscribe: 'Abonnieren',
    all_rights_reserved: 'Alle Rechte vorbehalten.'
  },
  hi: {
    // Navbar
    trips: 'यात्राएं',
    shared_trips: 'साझा यात्राएं',
    weather: 'मौसम',
    tracker: 'ट्रैकर',
    hotels: 'होटल',
    budgets: 'बजट',
    logged_in_as: 'लॉग इन किया है',
    profile: 'प्रोफ़ाइल',
    logout: 'लॉग आउट',
    light_mode: 'लाइट मोड',
    dark_mode: 'डार्क मोड',
    vault: 'तिजोरी',
    community: 'कम्युनिटी',
    sign_in: 'साइन इन करें',
    sign_up: 'साइन अप करें',
    go_to_dashboard: 'डैशबोर्ड पर जाएं',
    get_started_free: 'शुरू करें, यह मुफ़्त है',
    scroll_down_planner: 'योजनाकार खोलने के लिए नीचे स्क्रॉल करें',

    // Sky Radar / Tracker Page
    live_tracker: 'लाइव एविएशन रडार',
    sky_radar: 'स्काई रडार',
    live_api: 'लाइव',
    simulated_radar: 'सिम्युलेटेड रडार',
    tracked: 'ट्रैक किया गया',
    avg_speed: 'औसत गति',
    avg_altitude: 'औसत ऊंचाई',
    search_placeholder: 'फ्लाइट नंबर या देश खोजें...',
    scanning_skies: 'आसमान में विमानों की खोज की जा रही है...',
    error_connecting: 'फ्लाइट सर्वर से जुड़ने में असमर्थ...',
    try_again: 'पुनः प्रयास करें',
    next_update: 'अगला अपडेट',
    full_map: 'पूरा नक्शा',
    show_radar_list: 'सूची दिखाएं',
    en_route: 'मार्ग में',
    origin: 'प्रस्थान',
    dest: 'गंतव्य',
    heading: 'दिशा',
    speed: 'गति',
    altitude: 'ऊंचाई',
    vrate: 'वर्टिकल रेट',
    legend_title: 'ऊंचाई का नक्शा',
    legend_cruising: 'क्रूज़िंग (> ३०,००० फीट)',
    legend_transition: 'संक्रमण (१०,००० - ३०,००० फीट)',
    legend_approach: 'टेकऑफ़/लैंडिंग (< १०,००० फीट)',
    legend_selected: 'चयनित विमान',

    // Dashboard / Trips Page
    travel_hub: 'व्यक्तिगत यात्रा केंद्र',
    dashboard_title: 'मेरी यात्रा डैशबोर्ड',
    dashboard_desc: 'अपनी अनुकूलित यात्रा कार्यक्रम बनाएं और प्रबंधित करें।',
    create_new_trip: 'नई यात्रा बनाएं',
    recommended_trips: 'अनुशंसित पूर्व-नियोजित यात्राएं',
    days_schedule: 'दिनों का कस्टम शेड्यूल',
    travelers: 'यात्री',
    my_saved_itineraries: 'मेरे सहेजे गए यात्रा कार्यक्रम',
    loading_saved: 'सहेजे गए यात्रा कार्यक्रमों को लोड किया जा रहा है...',
    no_trips: 'अभी तक कोई यात्रा नहीं बनाई गई है',
    get_started: 'अपने पहले कस्टम यात्रा कार्यक्रम की योजना बनाकर शुरुआत करें।',
    start_planning: 'योजना बनाना शुरू करें',
    day: 'दिन',
    days: 'दिन',
    budget_label: 'बजट',
    my_travel_journey: 'मेरी यात्रा गाथा',
    total_spend: 'कुल खर्च',
    regions_visited: 'देखे गए क्षेत्र',
    destinations_count: 'गंतव्य',
    destination_count: 'गंतव्य',
    days_traveled: 'यात्रा के दिन',
    days_unit: 'दिन',
    travel_vibe: 'यात्रा शैली',
    passport_stamp_collection: 'पासपोर्ट स्टाम्प संग्रह',
    passport_stamp_subtitle: 'प्रत्येक नियोजित यात्रा आपके डिजिटल पासपोर्ट में एक स्टाम्प जोड़ती है।',
    stamps_label: 'स्टाम्प',
    passport_empty_title: 'आपका पासपोर्ट खाली है',
    passport_empty_desc: 'स्थानों के स्टाम्प एकत्र करने के लिए अपनी पहली यात्रा जोड़ें!',
    travel_milestones_title: 'यात्रा उपलब्धियां और मील के पत्थर',
    travel_milestones_subtitle: 'अद्वितीय यात्रा बैज अनलॉक करने और अपनी उपलब्धियों को ट्रैक करने के लिए और अधिक घूमें।',
    unlocked_label: 'अनलॉक',
    locked_label: 'लॉक',
    goal_label: 'लक्ष्य',
    daily_vibe: 'दैनिक विचार',
    wanderlust_quotes: 'यात्रा प्रेरणा उद्धरण',
    grid_view: 'ग्रिड व्यू',
    map_view: 'नक्शा व्यू',
    ask_xplorism_ai: 'Xplorism AI से पूछें',
    online_assistant: 'ऑनलाइन सहायक',
    chat_welcome_title: 'नमस्ते',
    chat_welcome_subtitle: 'मैं यात्रा कार्यक्रम बना सकता हूँ, मौसम/होटल देख सकता हूँ और गंतव्य खोज सकता हूँ। मुझसे कुछ भी पूछें!',
    chat_placeholder: 'Xplorism AI से पूछें...',
    regenerate_response: 'उत्तर पुनः उत्पन्न करें',
    clear_conversation: 'बातचीत साफ़ करें',
    thinking: 'सोच रहा है...',
    login_to_chat: 'चैट करने के लिए लॉगिन करें',
    chat_guest_desc: 'आपका AI यात्रा गाइड अनुकूलित यात्रा कार्यक्रम और गंतव्य जानकारी साझा करने के लिए तैयार है।',
    delete_chat_title: 'चैट हटाएं',
    delete_chat_confirm: 'क्या आप वाकई इस चैट को स्थायी रूप से हटाना चाहते हैं? यह कार्रवाई पूर्ववत नहीं की जा सकती।',
    cancel_action: 'रद्द करें',
    delete_action: 'हटाएं',
    deleting_action: 'हटाया जा रहा है...',

    // Profile Page
    profile_title: 'उपयोगकर्ता प्रोफ़ाइल',
    profile_desc: 'अपनी खाता सेटिंग, प्राथमिकताएं और आंकड़े प्रबंधित करें।',
    back_to_dashboard: 'डैशबोर्ड पर वापस जाएं',
    joined: 'शामिल हुए',
    google_account_linked: 'गूगल खाता लिंक किया गया',
    log_out_session: 'सत्र से लॉग आउट करें',
    travel_stats: 'आपके यात्रा आंकड़े',
    trips_planned: 'नियोजित यात्राएं',
    total_itineraries: 'उत्पन्न की गई कुल यात्रा कार्यक्रम',
    favorites: 'पसंदीदा',
    saved_locations: 'सहेजे गए स्थान और होटल',
    total_estimated_budget: 'कुल अनुमानित बजट',
    total_spent: 'नियोजित यात्राओं का कुल मूल्य',
    account_details: 'खाता विवरण',
    full_name: 'पूरा नाम',
    email_address: 'ईमेल पता',
    change_password_label: 'पासवर्ड बदलें',
    new_password_label: 'नया पासवर्ड',
    confirm_new_password_label: 'नए पासवर्ड की पुष्टि करें',
    security_checklist: 'सुरक्षा चेकलिस्ट',
    travel_preferences_title: 'यात्रा प्राथमिकताएं',
    preferred_style: 'पसंदीदा यात्रा शैली',
    preferred_currency: 'पसंदीदा मुद्रा',
    email_notifications: 'ईमेल सूचनाएं',
    recommendations_desc: 'सिफारिशें और यात्रा अनुस्मारक',
    weekly_digest: 'साप-साप्ताहिक सारांश',
    curated_news_desc: 'क्यूरेटेड न्यूजलेटर और यात्रा सौदे',
    favorite_themes: 'पसंदीदा यात्रा थीम',
    save_preferences: 'प्राथमिकताएं सहेजें',
    save_changes: 'परिवर्तन सहेजें',

    // Travel Styles Options
    style_adventure: 'साहसिक और अन्वेषण',
    style_leisure: 'विश्राम और आराम',
    style_balanced: 'संतुलित मिश्रण',
    style_budget: 'बजट बैकपैकिंग',
    style_culinary: 'पाक कला और संस्कृति',

    // Weather Page
    climate_radar: 'जलवायु और वातावरण',
    global_weather_forecast: 'वैश्विक मौसम पूर्वानुमान',
    weather_desc: 'अपनी अगली यात्रा बुक करने से पहले वास्तविक समय की जलवायु की जाँच करें।',
    search_city_placeholder: 'शहर खोजें, जैसे न्यू यॉर्क, लंदन, टोक्यो...',
    gathering_forecasts: 'स्थानीय वायुमंडलीय पूर्वानुमान एकत्र किए जा रहे हैं...',
    feels_like: 'ऐसा महसूस होता है',
    humidity_label: 'आर्द्रता',
    wind_speed_label: 'हवा की गति',
    extended_outlook: 'विस्तारित 7-दिवसीय आउटलुक',
    today: 'आज',
    discover_climates: 'वैश्विक जलवायु की खोज करें',
    discover_climates_desc: 'वायुमंडलीय स्थितियों का मानचित्र बनाने और 7-दिवसीय मौसम पूर्वानुमान प्राप्त करने के लिए ऊपर सर्च बार में कोई भी शहर दर्ज करें।',
    powered_by: 'मौसम डेटा ओपन-मेटियो द्वारा संचालित है।',

    // Weather Codes Options
    weather_clear_sky: 'साफ आसमान',
    weather_mainly_clear: 'मुख्य रूप से साफ',
    weather_partly_cloudy: 'आंशिक रूप से बादल छाए रहेंगे',
    weather_overcast: 'घने बादल',
    weather_foggy: 'कोहरा',
    weather_rime_fog: 'बर्फ का कोहरा',
    weather_light_drizzle: 'हल्की बूंदाबांदी',
    weather_moderate_drizzle: 'मध्यम बूंदाबांदी',
    weather_dense_drizzle: 'घनी बूंदाबांदी',
    weather_slight_rain: 'हल्की बारिश',
    weather_moderate_rain: 'मध्यम बारिश',
    weather_heavy_rain: 'भारी बारिश',
    weather_slight_snow: 'हल्की बर्फबारी',
    weather_moderate_snow: 'मध्यम बर्फबारी',
    weather_heavy_snow: 'भारी बर्फबारी',
    weather_slight_showers: 'हल्की बौछारें',
    weather_moderate_showers: 'मध्यम बौछारें',
    weather_violent_showers: 'तेज बौछारें',
    weather_thunderstorm: 'गरज के साथ बौछारें',
    weather_thunder_hail: 'ओलों के साथ आंधी',
    weather_heavy_thunder: 'भारी आंधी',

    // Budgets List Page
    financial_overview: 'वित्तीय अवलोकन',
    my_saved_budgets: 'मेरे सहेजे गए बजट',
    budgets_desc: 'सभी सहेजे गए यात्रा कार्यक्रमों में खर्चों की निगरानी, ​​​​ट्रैक और बजट प्रबंधित करें।',
    aggregating_budgets: 'बजट गणनाओं को एकत्रित किया जा रहा है...',
    no_budgets: 'कोई यात्रा कार्यक्रम बजट दर्ज नहीं किया गया',
    no_budgets_desc: 'वास्तविक समय के बजट को ट्रैक करने और खर्चों को लॉग करने के लिए पहले एक कस्टम यात्रा कार्यक्रम बनाएं और सहेजें।',
    budget_limit: 'सीमा',
    budget_spent: 'खर्च किया गया',
    budget_utilization: 'उपयोग',
    allocation_breakdown: 'आवंटन विवरण',
    edit_log_expenses: 'खर्चों को संपादित और लॉग करें',

    // Categories Options
    category_accommodation: 'आवास',
    category_food_dining: 'भोजन',
    category_activities_tours: 'गतिविधियाँ',
    category_transportation: 'परिवहन',
    category_shopping: 'खरीदारी',
    category_miscellaneous: 'विविध',

    // Budget Details Page
    budget_tracker: 'बजट ट्रैकर',
    date_schedule: 'तारीख अनुसूची',
    traveler: 'यात्री',
    starting_budget: 'शुरुआती बजट',
    calculating_breakdowns: 'नियोजित विवरणों की गणना की जा रही है...',
    no_budget_data: 'कोई बजट डेटा उपलब्ध नहीं है',
    no_budget_data_desc: "हम इस यात्रा कार्यक्रम के लिए बजट ट्रैकर्स की गणना नहीं कर सके।",
    budget_planned: 'नियोजित',
    tracked_expenses_desc: 'वास्तविक समय ट्रैक किए गए खर्च',
    remaining_funds: 'शेष',
    leftover_funds: 'बची हुई धनराशि',
    utilization_progress: 'बजट उपयोग प्रगति',
    utilization_progress_desc: 'कुल बजट सीमा के सापेक्ष वर्तमान खर्च दिखाता है',
    add_new_expense: 'नया खर्च जोड़ें',
    category_label: 'श्रेणी',
    item_name_label: 'मद का नाम',
    date_label: 'तारीख',
    notes_label: 'टिप्पणी (वैकल्पिक)',
    planned_cost: 'नियोजित बजट',
    actual_spent: 'वास्तविक खर्च *',
    actions: 'कार्रवाई',
    no_expenses_logged: 'अभी तक कोई खर्च दर्ज नहीं किया गया है।',
    add_first_expense_desc: 'खर्चों को लॉग करना शुरू करने के लिए नया खर्च जोड़ें पर क्लिक करें।',
    item: 'मद',
    items: 'मदें',
    of: 'का',
    save_expense: 'खर्च सहेजें',
    expense_history: 'खर्च इतिहास',
    item_placeholder: 'जैसे. बिस्ट्रो में रात का भोजन',
    notes_placeholder: 'कोई अतिरिक्त विवरण',
    cancel: 'रद्द करें',

    // Toast Notifications
    toast_trip_not_found: 'यात्रा नहीं मिली',
    toast_load_trip_fail: 'यात्रा विवरण लोड करने में विफल।',
    toast_load_budget_fail: 'बजट विवरण लोड करने में विफल।',
    toast_fill_fields: 'कृपया राशि और तारीख भरें।',
    toast_expense_added: 'खर्च सफलतापूर्वक जोड़ा गया!',
    toast_add_expense_fail: 'खर्च जोड़ने में विफल।',
    toast_expense_updated: 'खर्च सफलतापूर्वक अपडेट किया गया!',
    toast_update_expense_fail: 'खर्च अपडेट करने में विफल।',
    toast_expense_deleted: 'खर्च हटा दिया गया।',
    toast_delete_expense_fail: 'खर्च हटाने में विफल।',
    toast_load_itineraries_fail: 'सहेजे गए यात्रा कार्यक्रमों को लोड करने में विफल।',
    toast_save_trip_success: 'यात्रा कार्यक्रम सफलतापूर्वक सहेजा गया!',
    toast_save_trip_fail: 'यात्रा सहेजने में विफल।',

    // Vault Page
    secure_storage: 'एन्क्रिप्टेड स्टोरेज',
    vault_title: 'दस्तावेज़ तिजोरी',
    vault_subtitle: 'अपने आवश्यक यात्रा दस्तावेज़ों को सुरक्षित रूप से संग्रहीत और प्रबंधित करें।',
    add_document: 'दस्तावेज़ जोड़ें',
    expiry_warning: 'जल्द ही समाप्त हो रहा है!',
    expired: 'समाप्त हो गया!',
    passport: 'पासपोर्ट',
    visa: 'वीज़ा',
    ticket: 'टिकट',
    hotel_voucher: 'होटल वाउचर',
    insurance: 'बीमा',
    other: 'अन्य',
    doc_number: 'दस्तावेज़ संख्या',
    expiry_date: 'समाप्ति तिथि',
    notes: 'नोट्स / विवरण',
    file_upload: 'फ़ाइल अपलोड करें',
    save: 'सहेजें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    download: 'डाउनलोड करें',
    confirm_delete: 'क्या आप वाकई इस दस्तावेज़ को हटाना चाहते हैं?',
    no_documents: 'आपकी तिजोरी में कोई दस्तावेज़ नहीं है। एक जोड़कर शुरू करें!',
    // Community Feed Page
    community_feed: 'खोजकर्ताओं का सामाजिक फ़ीड',
    community_subtitle: 'दुनिया भर के सह-यात्रियों के साथ अनुभव साझा करें, पलों को रेखांकित करें और बातचीत करें।',
    share_experience: 'अनुभव साझा करें',
    search_posts_placeholder: 'टैग, उपयोगकर्ता या कीवर्ड द्वारा पोस्ट खोजें...',
    no_stories_title: 'अभी तक कोई कहानी साझा नहीं की गई',
    no_stories_desc: 'अपनी यात्राओं के बारे में लिखने और तस्वीरें पोस्ट करने वाले पहले यात्री बनें!',
    start_writing: 'लिखना शुरू करें',
    loading_social_logs: 'सामाजिक लॉग लोड हो रहे हैं...',
    edit_experience: 'अनुभव संपादित करें',
    share_an_experience: 'एक अनुभव साझा करें',
    experience_title: 'अनुभव का शीर्षक',
    hashtags: 'हैशटैग',
    type_tag_placeholder: 'टैग टाइप करें और स्पेस/एंटर दबाएं',
    add_more: 'और जोड़ें...',
    tell_story: 'कहानी बताएं',
    tell_story_placeholder: 'हमें बताएं कि आपने क्या अनुभव किया, बचत युक्तियाँ या मुख्य बातें...',
    add_photos_label: 'मुख्य तस्वीरें जोड़ें (अधिकतम 5)',
    upload_trip_pictures: 'यात्रा की तस्वीरें अपलोड करें',
    upload_trip_pictures_sub: 'एकाधिक छवियों का समर्थन करता है (अधिकतम 5, प्रत्येक 8 एमबी)',
    publishing: 'प्रकाशित हो रहा है...',
    save_changes: 'परिवर्तन सहेजें',
    post_experience: 'अनुभव पोस्ट करें',
    confirm_delete_post: 'क्या आप वाकई इस पोस्ट को हटाना चाहते हैं?',
    likes: 'पसंद',
    toast_post_deleted: 'पोस्ट सफलतापूर्वक हटा दिया गया',
    deleting: 'हटाया जा रहा है...',
    // Footer
    footer_slogan: 'आसान योजना बनाएं, बेहतर यात्रा करें। व्यक्तिगत यात्रा कार्यक्रमों, वास्तविक समय के अपडेट और सहयोगी नियोजन टूल के साथ दुनिया का अनुभव करें।',
    features_title: 'विशेषताएं',
    resources_title: 'संसाधन',
    stay_updated: 'अपडेट रहें',
    itinerary_builder: 'यात्रा कार्यक्रम निर्माता',
    interactive_map: 'इंटरैक्टिव मानचित्र',
    weather_forecast: 'मौसम का पूर्वानुमान',
    budget_manager: 'बजट प्रबंधक',
    document_vault: 'दस्तावेज़ तिजोरी',
    travel_guides: 'यात्रा गाइड',
    help_center: 'सहायता केंद्र',
    community_feed_footer: 'कम्युनिटी फीड',
    terms_of_service: 'सेवा की शर्तें',
    privacy_policy: 'गोपनीयता नीति',
    cookie_settings: 'कुकी सेटिंग्स',
    newsletter_desc: 'नवीनतम यात्रा गाइड, टिप्स और फीचर अपडेट के लिए हमारे न्यूज़लेटर को सब्सक्राइब करें।',
    email_placeholder: 'अपना ईमेल दर्ज करें',
    subscribe: 'सब्सक्राइब',
    all_rights_reserved: 'सर्वाधिकार सुरक्षित।'
  },
  ar: {
    // Navbar
    trips: 'رحلاتي',
    shared_trips: 'الرحلات المشتركة',
    weather: 'الطقس',
    tracker: 'الرادار',
    hotels: 'الفنادق',
    budgets: 'الميزانية',
    logged_in_as: 'مسجل كـ',
    profile: 'الملف الشخصي',
    logout: 'تسجيل الخروج',
    light_mode: 'وضع فاتح',
    dark_mode: 'وضع داكن',
    vault: 'الخزنة',
    community: 'المجتمع',
    sign_in: 'تسجيل الدخول',
    sign_up: 'إنشاء حساب',
    go_to_dashboard: 'الانتقال إلى لوحة التحكم',
    get_started_free: 'ابدأ الآن، إنه مجاني',
    scroll_down_planner: 'انزل لأسفل لفتح مخططك',

    // Sky Radar / Tracker Page
    live_tracker: 'رادار الطيران المباشر',
    sky_radar: 'رادار السماء',
    live_api: 'مباشر',
    simulated_radar: 'رادار محاكي',
    tracked: 'المتتبع',
    avg_speed: 'متوسط السرعة',
    avg_altitude: 'متوسط الارتفاع',
    search_placeholder: 'بحث برقم الرحلة أو البلد...',
    scanning_skies: 'جاري مسح السماء بحثاً عن طائرات...',
    error_connecting: 'تعذر الاتصال بخادم الرحلة...',
    try_again: 'أعد المحاولة',
    next_update: 'التحديث القادم في',
    full_map: 'الخريطة الكاملة',
    show_radar_list: 'عرض القائمة',
    en_route: 'في الطريق',
    origin: 'المنشأ',
    dest: 'الوجهة',
    heading: 'الاتجاه',
    speed: 'السرعة',
    altitude: 'الارتفاع',
    vrate: 'المعدل العمودي',
    legend_title: 'دليل الارتفاع',
    legend_cruising: 'طيران مستقر (> ٣٠ ألف قدم)',
    legend_transition: 'ارتفاع انتقالي (١٠-٣٠ ألف قدم)',
    legend_approach: 'إقلاع وهبوط (< ١٠ آلاف قدم)',
    legend_selected: 'الطائرة المحددة',

    // Dashboard / Trips Page
    travel_hub: 'مركز السفر الشخصي',
    dashboard_title: 'لوحة رحلاتي',
    dashboard_desc: 'إنشاء وإدارة مساراتك المخصصة.',
    create_new_trip: 'إنشاء رحلة جديدة',
    recommended_trips: 'رحلات ما قبل التخطيط الموصى بها',
    days_schedule: 'أيام جدول مخصص',
    travelers: 'مسافرين',
    my_saved_itineraries: 'مساراتي المحفوظة',
    loading_saved: 'جاري تحميل مساراتك المحفوظة...',
    no_trips: 'لم يتم إنشاء أي رحلات بعد',
    get_started: 'ابدأ بالتخطيط لأول مسار سفر مخصص لك.',
    start_planning: 'ابدأ التخطيط',
    day: 'يوم',
    days: 'أيام',
    budget_label: 'الميزانية',
    my_travel_journey: 'رحلتي واستكشافاتي',
    total_spend: 'إجمالي الإنفاق',
    regions_visited: 'المناطق التي زرتها',
    destinations_count: 'وجهات',
    destination_count: 'وجهة',
    days_traveled: 'أيام السفر',
    days_unit: 'أيام',
    travel_vibe: 'طابع السفر',
    passport_stamp_collection: 'مجموعة أختام جواز السفر',
    passport_stamp_subtitle: 'كل رحلة مخطط لها تضيف ختماً إلى جواز سفرك الرقمي.',
    stamps_label: 'أختام',
    passport_empty_title: 'جواز سفرك فارغ',
    passport_empty_desc: 'أضف رحلتك الأولى لتبدأ في جمع أختام الوجهات الرائعة!',
    travel_milestones_title: 'إنجازات السفر والجوائز',
    travel_milestones_subtitle: 'استكشف أكثر لفتح شارات السفر الفريدة وتتبع إنجازاتك.',
    unlocked_label: 'مفتوح',
    locked_label: 'مغلق',
    goal_label: 'الهدف',
    daily_vibe: 'إلهام يومي',
    wanderlust_quotes: 'اقتباسات السفر الملهمة',
    grid_view: 'عرض الشبكة',
    map_view: 'عرض الخريطة',
    ask_xplorism_ai: 'اسأل ذكاء Xplorism',
    online_assistant: 'مساعد متصل',
    chat_welcome_title: 'مرحباً',
    chat_welcome_subtitle: 'يمكنني إنشاء خطط رحلات، التحقق من الطقس والفنادق، والبحث عن الوجهات. اسألني أي شيء!',
    chat_placeholder: 'اسأل ذكاء Xplorism...',
    regenerate_response: 'إعادة إنشاء الرد',
    clear_conversation: 'مسح المحادثة',
    thinking: 'جاري التفكير...',
    login_to_chat: 'سجل الدخول لبدء المحادثة',
    chat_guest_desc: 'دليلك السياحي الذكي جاهز لاقتراح مسارات ووجهات مخصصة.',
    delete_chat_title: 'حذف المحادثة',
    delete_chat_confirm: 'هل أنت متأكد أنك تريد حذف هذه المحادثة نهائياً؟ لا يمكن التراجع عن هذا الإجراء.',
    cancel_action: 'إلغاء',
    delete_action: 'حذف',
    deleting_action: 'جاري الحذف...',

    // Profile Page
    profile_title: 'ملف المستخدم',
    profile_desc: 'إدارة إعدادات حسابك، وتفضيلاتك، وعرض إحصائياتك.',
    back_to_dashboard: 'العودة إلى لوحة القيادة',
    joined: 'انضم في',
    google_account_linked: 'حساب Google مرتبط',
    log_out_session: 'تسجيل الخروج من الجلسة',
    travel_stats: 'إحصاءات سفرك',
    trips_planned: 'الرحلات المخططة',
    total_itineraries: 'إجمالي مسارات الرحلات المنشأة',
    favorites: 'المفضلة',
    saved_locations: 'المواقع والفنادق المحفوظة',
    total_estimated_budget: 'إجمالي الميزانية التقديرية',
    total_spent: 'القيمة الإجمالية للرحلات المخططة',
    account_details: 'تفاصيل الحساب',
    full_name: 'الاسم الكامل',
    email_address: 'عنوان البريد الإلكتروني',
    change_password_label: 'تغيير كلمة المرور',
    new_password_label: 'كلمة المرور الجديدة',
    confirm_new_password_label: 'تأكيد كلمة المرور الجديدة',
    security_checklist: 'قائمة مرجعية للأمان',
    travel_preferences_title: 'تفضيلات السفر',
    preferred_style: 'أسلوب السفر المفضل',
    preferred_currency: 'العملة المفضلة',
    email_notifications: 'إشعارات البريد الإلكتروني',
    recommendations_desc: 'التوصيات وتذكيرات الرحلات',
    weekly_digest: 'الموجز الأسبوعي',
    curated_news_desc: 'النشرات الإخبارية وعروض السفر المنسقة',
    favorite_themes: 'مواضيع السفر المفضلة',
    save_preferences: 'حفظ التفضيلات',
    save_changes: 'حفظ التغييرات',

    // Travel Styles Options
    style_adventure: 'مغامرة واستكشاف',
    style_leisure: 'الاسترخاء والترفيه',
    style_balanced: 'مزيج متوازن',
    style_budget: 'السفر بميزانية محدودة',
    style_culinary: 'المطبخ والثقافة',

    // Weather Page
    climate_radar: 'المناخ والطقس',
    global_weather_forecast: 'توقعات الطقس العالمية',
    weather_desc: 'تحقق من المناخ في الوقت الفعلي قبل حجز رحلتك القادمة.',
    search_city_placeholder: 'ابحث عن مدينة، مثل نيويورك، لندن، طوكيو...',
    gathering_forecasts: 'جاري جمع توقعات الطقس المحلية...',
    feels_like: 'الشعور الحقيقي',
    humidity_label: 'الرطوبة',
    wind_speed_label: 'سرعة الرياح',
    extended_outlook: 'توقعات موسعة لمدة 7 أيام',
    today: 'اليوم',
    discover_climates: 'اكتشف المناخ العالمي',
    discover_climates_desc: 'أدخل أي مدينة في شريط البحث أعلاه لمعاينة أحوالها الجوية واسترداد توقعات الطقس لمدة 7 أيام.',
    powered_by: 'بيانات المناخ مدعومة بواسطة Open-Meteo.',

    // Weather Codes Options
    weather_clear_sky: 'سماء صافية',
    weather_mainly_clear: 'صافٍ غالباً',
    weather_partly_cloudy: 'غائم جزئياً',
    weather_overcast: 'غائم كلياً',
    weather_foggy: 'ضباب',
    weather_rime_fog: 'ضباب صقيعي متراكم',
    weather_light_drizzle: 'رذاذ خفيف',
    weather_moderate_drizzle: 'رذاذ معتدل',
    weather_dense_drizzle: 'رذاذ كثيف',
    weather_slight_rain: 'مطر خفيف',
    weather_moderate_rain: 'مطر معتدل',
    weather_heavy_rain: 'مطر غزير',
    weather_slight_snow: 'تساقط ثلوج خفيفة',
    weather_moderate_snow: 'تساقط ثلوج معتدلة',
    weather_heavy_snow: 'تساقط ثلوج كثيفة',
    weather_slight_showers: 'زخات مطر خفيفة',
    weather_moderate_showers: 'زخات مطر معتدلة',
    weather_violent_showers: 'زخات مطر شديدة',
    weather_thunderstorm: 'عاصفة رعدية',
    weather_thunder_hail: 'عاصفة رعدية مع برد',
    weather_heavy_thunder: 'عاصفة رعدية شديدة',

    // Budgets List Page
    financial_overview: 'الملخص المالي',
    my_saved_budgets: 'ميزانياتي المحفوظة',
    budgets_desc: 'مراقبة وتتبع النفقات وإدارة الميزانيات عبر جميع مسارات الرحلة المحفوظة.',
    aggregating_budgets: 'جاري تجميع حسابات الميزانية...',
    no_budgets: 'لم يتم تسجيل ميزانية للمسارات',
    no_budgets_desc: 'قم بإنشاء وحفظ مسار رحلة مخصص أولاً لتتبع الميزانيات في الوقت الفعلي وتسجيل النفقات.',
    budget_limit: 'الحد الأقصى',
    budget_spent: 'المنفق',
    budget_utilization: 'الاستخدام',
    allocation_breakdown: 'تفاصيل التخصيص',
    edit_log_expenses: 'تعديل وتسجيل النفقات',

    // Categories Options
    category_accommodation: 'الإقامة',
    category_food_dining: 'الطعام',
    category_activities_tours: 'الأنشطة',
    category_transportation: 'النقل',
    category_shopping: 'التسوق',
    category_miscellaneous: 'متنوع',

    // Budget Details Page
    budget_tracker: 'تتبع الميزانية',
    date_schedule: 'جدول المواعيد',
    traveler: 'مسافر',
    starting_budget: 'الميزانية الأولية',
    calculating_breakdowns: 'جاري حساب التفاصيل المخططة...',
    no_budget_data: 'لا تتوفر بيانات الميزانية',
    no_budget_data_desc: "لم نتمكن من حساب تتبع الميزانية لهذا المسار.",
    budget_planned: 'المخطط',
    tracked_expenses_desc: 'النفقات المتبعة في الوقت الفعلي',
    remaining_funds: 'المتبقي',
    leftover_funds: 'الأموال المتبقية',
    utilization_progress: 'تقدم استخدام الميزانية',
    utilization_progress_desc: 'يوضح الإنفاق الحالي بالنسبة للحد الأقصى للميزانية',
    add_new_expense: 'إضافة نفقات جديدة',
    category_label: 'الفئة',
    item_name_label: 'اسم العنصر',
    date_label: 'التاريخ',
    notes_label: 'ملاحظات (إختياري)',
    planned_cost: 'التكلفة المخططة',
    actual_spent: 'الإنفاق الفعلي *',
    actions: 'الإجراءات',
    no_expenses_logged: 'لم يتم تسجيل أي نفقات بعد.',
    add_first_expense_desc: 'انقر فوق إضافة نفقات جديدة لبدء تسجيل التكاليف.',
    item: 'عنصر',
    items: 'عناصر',
    of: 'من',
    save_expense: 'حفظ النفقات',
    expense_history: 'سجل النفقات',
    item_placeholder: 'مثال: عشاء في مطعم',
    notes_placeholder: 'أي تفاصيل إضافية',
    cancel: 'إلغاء',

    // Toast Notifications
    toast_trip_not_found: 'الرحلة غير موجودة',
    toast_load_trip_fail: 'فشل في تحميل تفاصيل الرحلة.',
    toast_load_budget_fail: 'فشل في تحميل تفاصيل الميزانية.',
    toast_fill_fields: 'يرجى ملء المبلغ والتاريخ.',
    toast_expense_added: 'تم إضافة النفقة بنجاح!',
    toast_add_expense_fail: 'فشل إضافة النفقة.',
    toast_expense_updated: 'تم تحديث النفقة بنجاح!',
    toast_update_expense_fail: 'فشل تحديث النفقة.',
    toast_expense_deleted: 'تم حذف النفقة.',
    toast_delete_expense_fail: 'فشل حذف النفقة.',
    toast_load_itineraries_fail: 'فشل تحميل مسارات الرحلة.',
    toast_save_trip_success: 'تم حفظ مسار الرحلة بنجاح!',
    toast_save_trip_fail: 'فشل حفظ الرحلة.',

    // Vault Page
    secure_storage: 'تخزين مشفر',
    vault_title: 'خزنة المستندات',
    vault_subtitle: 'قم بتخزين مستندات السفر الهامة الخاصة بك بشكل آمن.',
    add_document: 'إضافة مستند',
    expiry_warning: 'ينتهي قريباً!',
    expired: 'منتهي صلاحيته!',
    passport: 'جواز سفر',
    visa: 'تأشيرة دخول',
    ticket: 'تذكرة',
    hotel_voucher: 'حجز الفندق',
    insurance: 'تأمين السفر',
    other: 'أخرى',
    doc_number: 'رقم المستند',
    expiry_date: 'تاريخ الانتهاء',
    notes: 'ملاحظات / تفاصيل',
    file_upload: 'تحميل ملف',
    save: 'حفظ',
    delete: 'حذف',
    edit: 'تعديل',
    download: 'تحميل',
    confirm_delete: 'هل أنت متأكد من حذف هذا المستند؟',
    no_documents: 'لا توجد مستندات في الخزنة. ابدأ بإضافة مستند جديد!',
    // Community Feed Page
    community_feed: 'خلاصة مجتمع المستكشفين',
    community_subtitle: 'شارك سجلات السفر، وسلط الضوء على اللحظات، وتفاعل مع المسافرين الآخرين من جميع أنحاء العالم.',
    share_experience: 'شارك تجربة',
    search_posts_placeholder: 'البحث عن منشورات بواسطة الوسوم، المستخدم، أو الكلمات المفتاحية...',
    no_stories_title: 'لم يتم مشاركة أي قصص بعد',
    no_stories_desc: 'كن أول مسافر يكتب سجلاً وينشر صوراً عن مغامراته!',
    start_writing: 'ابدأ الكتابة',
    loading_social_logs: 'جاري تحميل المنشورات...',
    edit_experience: 'تعديل التجربة',
    share_an_experience: 'مشاركة تجربة سفر',
    experience_title: 'عنوان التجربة',
    hashtags: 'الوسوم (هاشتاق)',
    type_tag_placeholder: 'اكتب الوسم واضغط مسافة أو إدخال',
    add_more: 'أضف المزيد...',
    tell_story: 'احكِ القصة',
    tell_story_placeholder: 'أخبرنا عما عشته، نصائح لتوفير المال، أو أبرز اللحظات...',
    add_photos_label: 'إضافة صور مميزة (الحد الأقصى 5)',
    upload_trip_pictures: 'تحميل صور الرحلة',
    upload_trip_pictures_sub: 'يدعم صوراً متعددة (بحد أقصى 5، سعة 8 ميجابايت لكل منها)',
    publishing: 'جاري النشر...',
    save_changes: 'حفظ التغييرات',
    post_experience: 'نشر التجربة',
    confirm_delete_post: 'هل أنت متأكد أنك تريد حذف هذا المنشور؟',
    likes: 'إعجابات',
    toast_post_deleted: 'تم حذف المنشور بنجاح',
    deleting: 'جاري الحذف...',
    // Footer
    footer_slogan: 'خطط بشكل أبسط، وسافر بشكل أفضل. اختبر العالم بمسارات مخصصة، وتحديثات في الوقت الفعلي، وأدوات تخطيط تعاونية.',
    features_title: 'الميزات',
    resources_title: 'الموارد',
    stay_updated: 'ابق على اطلاع',
    itinerary_builder: 'مخطط الرحلة',
    interactive_map: 'الخريطة التفاعلية',
    weather_forecast: 'توقعات الطقس',
    budget_manager: 'مدير الميزانية',
    document_vault: 'خزنة المستندات',
    travel_guides: 'أدلة السفر',
    help_center: 'مركز المساعدة',
    community_feed_footer: 'خلاصة المجتمع',
    terms_of_service: 'شروط الخدمة',
    privacy_policy: 'سياسة الخصوصية',
    cookie_settings: 'إعدادات ملفات تعريف الارتباط',
    newsletter_desc: 'اشترك في نشرتنا الإخبارية للحصول على أحدث أدلة السفر والنصائح وتحديثات الميزات.',
    email_placeholder: 'أدخل بريدك الإلكتروني',
    subscribe: 'اشتراك',
    all_rights_reserved: 'جميع الحقوق محفوظة.'
  },
  pt: {
    // Navbar
    trips: 'Viagens',
    shared_trips: 'Viagens Partilhadas',
    weather: 'Clima',
    tracker: 'Rastreador',
    hotels: 'Hotéis',
    budgets: 'Orçamentos',
    logged_in_as: 'Sessão como',
    profile: 'Perfil',
    logout: 'Sair',
    light_mode: 'Modo Claro',
    dark_mode: 'Modo Escuro',
    vault: 'Cofre',
    community: 'Comunidade',
    sign_in: 'Entrar',
    sign_up: 'Cadastrar-se',
    go_to_dashboard: 'Ir para o Painel',
    get_started_free: 'Começar, é Grátis',
    scroll_down_planner: 'Role para baixo para abrir o planejador',

    // Tracker Page
    sky_radar: 'Radar Aéreo',
    live_api: 'Ao Vivo',
    simulated_radar: 'Radar Simulado',
    tracked: 'Rastreados',
    avg_speed: 'Vel. Média',
    avg_altitude: 'Alt. Média',
    search_placeholder: 'Buscar voo ou país...',
    scanning_skies: 'Rastreando aviões nos céus...',
    error_connecting: 'Não foi possível conectar ao servidor...',
    try_again: 'Tentar novamente',
    next_update: 'Próxima atualização em',
    full_map: 'Mapa Completo',
    show_radar_list: 'Mostrar Lista',
    en_route: 'EM ROTA',
    origin: 'Origem',
    dest: 'Destino',
    heading: 'Rumo',
    speed: 'Velocidade',
    altitude: 'Altitude',
    vrate: 'Taxa Vertical',
    legend_title: 'Legenda de Altitude',
    legend_cruising: 'Cruzeiro (> 30.000 ft)',
    legend_transition: 'Transição (10k - 30k ft)',
    legend_approach: 'Decolagem/Pouso (< 10k ft)',
    legend_selected: 'Aeronave Selecionada',

    // Dashboard / Trips Page
    travel_hub: 'Centro de viagens pessoal',
    dashboard_title: 'Meu Painel de Viagens',
    dashboard_desc: 'Crie e gerencie seus roteiros personalizados.',
    create_new_trip: 'Criar Nova Viagem',
    recommended_trips: 'Viagens Recomendadas Pré-planejadas',
    days_schedule: 'Dias de Programação Personalizada',
    travelers: 'Viajantes',
    my_saved_itineraries: 'Meus Roteiros Salvos',
    loading_saved: 'Carregando roteiros salvos...',
    no_trips: 'Nenhuma viagem criada ainda',
    get_started: 'Comece planejando seu primeiro roteiro de viagem personalizado.',
    start_planning: 'Começar Planejamento',
    day: 'dia',
    days: 'dias',
    budget_label: 'Orçamento',
    my_travel_journey: 'Minha Jornada de Viagens',
    total_spend: 'Gasto Total',
    regions_visited: 'Regiões Visitadas',
    destinations_count: 'Destinos',
    destination_count: 'Destino',
    days_traveled: 'Dias Viajados',
    days_unit: 'Dias',
    travel_vibe: 'Estilo de Viagem',
    passport_stamp_collection: 'Coleção de Carimbos no Passaporte',
    passport_stamp_subtitle: 'Cada viagem planejada adiciona um carimbo ao seu passaporte digital.',
    stamps_label: 'Carimbos',
    passport_empty_title: 'Seu passaporte está vazio',
    passport_empty_desc: 'Adicione sua primeira viagem para começar a colecionar carimbos!',
    travel_milestones_title: 'Conquistas e Marcos de Viagem',
    travel_milestones_subtitle: 'Explore mais para desbloquear medalhas e acompanhar suas conquistas.',
    unlocked_label: 'Desbloqueado',
    locked_label: 'Bloqueado',
    goal_label: 'Meta',
    daily_vibe: 'Inspiração Diária',
    wanderlust_quotes: 'Citações Inspiradoras',
    grid_view: 'Visualização em Grade',
    map_view: 'Visualização em Mapa',
    ask_xplorism_ai: 'Perguntar ao Xplorism IA',
    online_assistant: 'Assistente Online',
    chat_welcome_title: 'Olá',
    chat_welcome_subtitle: 'Posso criar roteiros de viagem, consultar previsão do tempo, hotéis e buscar destinos. Pergunte qualquer coisa!',
    chat_placeholder: 'Pergunte ao Xplorism IA...',
    regenerate_response: 'Regenerar resposta',
    clear_conversation: 'Limpar conversa',
    thinking: 'Pensando...',
    login_to_chat: 'Entrar para Conversar',
    chat_guest_desc: 'Seu guia de viagem inteligente está pronto para sugerir roteiros personalizados.',
    delete_chat_title: 'Excluir Conversa',
    delete_chat_confirm: 'Tem certeza de que deseja excluir permanentemente esta conversa? Esta ação não pode ser desfeita.',
    cancel_action: 'Cancelar',
    delete_action: 'Excluir',
    deleting_action: 'Excluindo...',

    // Profile Page
    profile_title: 'Perfil do Usuário',
    profile_desc: 'Gerencie as configurações da sua conta, preferências e veja suas estatísticas.',
    back_to_dashboard: 'Voltar ao Painel',
    joined: 'Registrado em',
    google_account_linked: 'Conta do Google Vinculada',
    log_out_session: 'Sair da Sessão',
    travel_stats: 'Estatísticas de Viagem',
    trips_planned: 'Viagens Planejadas',
    total_itineraries: 'Roteiros totais gerados',
    favorites: 'Favoritos',
    saved_locations: 'Locais e hotéis salvos',
    total_estimated_budget: 'Orçamento Total Estimado',
    total_spent: 'Custo acumulado das viagens',
    account_details: 'Detalhes da Conta',
    full_name: 'Nome Completo',
    email_address: 'Endereço de E-mail',
    change_password_label: 'Alterar Senha',
    new_password_label: 'Nova Senha',
    confirm_new_password_label: 'Confirmar Nova Senha',
    security_checklist: 'Lista de Segurança',
    travel_preferences_title: 'Preferências de Viagem',
    preferred_style: 'Estilo de Viagem Preferido',
    preferred_currency: 'Moeda Preferida',
    email_notifications: 'Notificações por E-mail',
    recommendations_desc: 'Recomendações e lembretes de viagem',
    weekly_digest: 'Resumo Semanal',
    curated_news_desc: 'Newsletters e ofertas de viagens',
    favorite_themes: 'Temas de Viagem Favoritos',
    save_preferences: 'Salvar Preferências',
    save_changes: 'Salvar Alterações',

    // Travel Styles Options
    style_adventure: 'Aventura e Exploração',
    style_leisure: 'Relaxamento e Lazer',
    style_balanced: 'Mistura Equilibrada',
    style_budget: 'Mochilão Econômico',
    style_culinary: 'Culinária e Cultura',

    // Weather Page
    climate_radar: 'Clima e Atmosfera',
    global_weather_forecast: 'Previsão do Tempo Global',
    weather_desc: 'Verifique as condições climáticas em tempo real antes de reservar sua próxima viagem.',
    search_city_placeholder: 'Buscar cidade, ex. Nova York, Londres, Tóquio...',
    gathering_forecasts: 'Coletando previsões atmosféricas locais...',
    feels_like: 'Sensação Térmica',
    humidity_label: 'Umidade',
    wind_speed_label: 'Vel. do Vento',
    extended_outlook: 'Previsão Estendida de 7 Dias',
    today: 'Hoje',
    discover_climates: 'Descobrir Climas Globais',
    discover_climates_desc: 'Digite qualquer cidade na barra de busca acima para ver suas condições atmosféricas e obter previsões para 7 dias.',
    powered_by: 'Dados climáticos fornecidos por Open-Meteo.',

    // Weather Codes Options
    weather_clear_sky: 'Céu Limpo',
    weather_mainly_clear: 'Predominantemente Limpo',
    weather_partly_cloudy: 'Partialmente Nublado',
    weather_overcast: 'Encoberto',
    weather_foggy: 'Névoa',
    weather_rime_fog: 'Névoa com Depósito de Gelo',
    weather_light_drizzle: 'Chuva Leve',
    weather_moderate_drizzle: 'Chuva Moderada',
    weather_dense_drizzle: 'Chuva Densa',
    weather_slight_rain: 'Chuva Fraca',
    weather_moderate_rain: 'Chuva Moderada',
    weather_heavy_rain: 'Chuva Forte',
    weather_slight_snow: 'Neve Fraca',
    weather_moderate_snow: 'Neve Moderada',
    weather_heavy_snow: 'Neve Forte',
    weather_slight_showers: 'Pancadas de Chuva Leves',
    weather_moderate_showers: 'Pancadas de Chuva Moderadas',
    weather_violent_showers: 'Pancadas de Chuva Fortes',
    weather_thunderstorm: 'Tempestade',
    weather_thunder_hail: 'Tempestade com Granizo',
    weather_heavy_thunder: 'Tempestade Forte',

    // Budgets List Page
    financial_overview: 'Visão Geral Financeira',
    my_saved_budgets: 'Meus Orçamentos Salvos',
    budgets_desc: 'Monitore, acompanhe despesas e gerencie orçamentos em seus roteiros personalizados.',
    aggregating_budgets: 'Agregando cálculos de orçamento...',
    no_budgets: 'Nenhum orçamento registrado',
    no_budgets_desc: 'Crie e salve um roteiro personalizado primeiro para acompanhar orçamentos e despesas.',
    budget_limit: 'Limite',
    budget_spent: 'Gasto',
    budget_utilization: 'Utilização',
    allocation_breakdown: 'Distribuição de Alocação',
    edit_log_expenses: 'Editar e Registrar Despesas',

    // Categories Options
    category_accommodation: 'Acomodação',
    category_food_dining: 'Alimentação',
    category_activities_tours: 'Atividades',
    category_transportation: 'Transporte',
    category_shopping: 'Compras',
    category_miscellaneous: 'Diversos',

    // Budget Details Page
    budget_tracker: 'Rastreador de Orçamento',
    date_schedule: 'Cronograma de Datas',
    traveler: 'Viajante',
    starting_budget: 'Orçamento Inicial',
    calculating_breakdowns: 'Calculando detalhamentos...',
    no_budget_data: 'Nenhum dado de orçamento disponível',
    no_budget_data_desc: "Não conseguimos calcular o orçamento para este roteiro.",
    budget_planned: 'Planejado',
    tracked_expenses_desc: 'Despesas rastreadas em tempo real',
    remaining_funds: 'Restante',
    leftover_funds: 'Fundos restantes',
    utilization_progress: 'Progresso de Utilização',
    utilization_progress_desc: 'Mostra o gasto atual em relação ao limite do orçamento.',
    add_new_expense: 'Adicionar Nova Despesa',
    category_label: 'Categoria',
    item_name_label: 'Nome do Item',
    date_label: 'Data',
    notes_label: 'Notas (opcional)',
    planned_cost: 'Custo Planejado',
    actual_spent: 'Gasto Real *',
    actions: 'Ações',
    no_expenses_logged: 'Nenhuma despesa registrada ainda.',
    add_first_expense_desc: 'Clique em Adicionar Nova Despesa para começar a registrar os custos.',
    item: 'item',
    items: 'itens',
    of: 'de',
    save_expense: 'Salvar Despesa',
    expense_history: 'Histórico de Despesas',
    item_placeholder: 'ex. Jantar no Bistro',
    notes_placeholder: 'Detalhes adicionais',
    cancel: 'Cancelar',

    // Toast Notifications
    toast_trip_not_found: 'Viagem não encontrada',
    toast_load_trip_fail: 'Erro ao carregar detalhes da viagem.',
    toast_load_budget_fail: 'Erro ao carregar detalhes do orçamento.',
    toast_fill_fields: 'Por favor, preencha o valor e a data.',
    toast_expense_added: 'Despesa adicionada com sucesso!',
    toast_add_expense_fail: 'Erro ao adicionar despesa.',
    toast_expense_updated: 'Despesa atualizada com sucesso!',
    toast_update_expense_fail: 'Erro ao atualizar despesa.',
    toast_expense_deleted: 'Despesa excluída.',
    toast_delete_expense_fail: 'Erro ao excluir despesa.',
    toast_load_itineraries_fail: 'Erro ao carregar roteiros salvos.',
    toast_save_trip_success: 'Roteiro salvo com sucesso!',
    toast_save_trip_fail: 'Erro ao salvar viagem.',

    // Vault Page
    secure_storage: 'Armazenamento Criptografado',
    vault_title: 'Cofre de Documentos',
    vault_subtitle: 'Guarde e gira com segurança seus documentos de viagem.',
    add_document: 'Adicionar Documento',
    expiry_warning: 'Expira em breve!',
    expired: 'Expirado!',
    passport: 'Passaporte',
    visa: 'Visto',
    ticket: 'Passagem',
    hotel_voucher: 'Voucher de Hotel',
    insurance: 'Seguro de Viagem',
    other: 'Outro',
    doc_number: 'Número do Documento',
    expiry_date: 'Data de Validade',
    notes: 'Notas / Detalhes',
    file_upload: 'Enviar Arquivo',
    save: 'Salvar',
    delete: 'Excluir',
    edit: 'Editar',
    download: 'Baixar',
    confirm_delete: 'Tem certeza que deseja excluir este documento?',
    no_documents: 'Nenhum documento armazenado. Comece adicionando um!',
    // Community Feed Page
    community_feed: 'Feed Social de Exploradores',
    community_subtitle: 'Partilhe relatos, destaque momentos e interaja com co-viajantes de todo o mundo.',
    share_experience: 'Partilhar Experiência',
    search_posts_placeholder: 'Pesquisar publicações por hashtags, utilizador ou palavras-chave...',
    no_stories_title: 'Nenhuma história partilhada ainda',
    no_stories_desc: 'Seja o primeiro viajante a escrever um relato e publicar fotos sobre as suas aventuras!',
    start_writing: 'Começar a Escrever',
    loading_social_logs: 'A carregar publicações...',
    edit_experience: 'Editar Experiência',
    share_an_experience: 'Partilhar uma Experiência',
    experience_title: 'Título da Experiência',
    hashtags: 'Hashtags',
    type_tag_placeholder: 'Escreva a tag e prima Espaço/Enter',
    add_more: 'adicionar mais...',
    tell_story: 'Conte a história',
    tell_story_placeholder: 'Conte-nos o que vivenciou, dicas de poupança ou momentos marcantes...',
    add_photos_label: 'Adicionar Fotos de Destaque (Máx 5)',
    upload_trip_pictures: 'Carregar Fotos da Viagem',
    upload_trip_pictures_sub: 'Suporta várias imagens (Máx 5, 8MB cada)',
    publishing: 'A publicar...',
    save_changes: 'Guardar Alterações',
    post_experience: 'Publicar Experiencia',
    confirm_delete_post: 'Tem a certeza de que deseja eliminar esta publicação?',
    likes: 'Gostos',
    toast_post_deleted: 'Publicação eliminada com sucesso',
    deleting: 'A eliminar...',
    // Footer
    footer_slogan: 'Planeje de forma mais simples, viaje melhor. Experimente o mundo com itinerários personalizados, atualizações em tempo real e ferramentas de planejamento colaborativo.',
    features_title: 'Recursos',
    resources_title: 'Recursos Úteis',
    stay_updated: 'Fique Atualizado',
    itinerary_builder: 'Criador de Roteiros',
    interactive_map: 'Mapa Interativo',
    weather_forecast: 'Previsão do Tempo',
    budget_manager: 'Gerenciador de Orçamento',
    document_vault: 'Cofre de Documentos',
    travel_guides: 'Guias de Viagem',
    help_center: 'Central de Ajuda',
    community_feed_footer: 'Feed da Comunidade',
    terms_of_service: 'Termos de Serviço',
    privacy_policy: 'Política de Privacidade',
    cookie_settings: 'Configurações de Cookies',
    newsletter_desc: 'Assine nossa newsletter para receber os últimos guias de viagem, dicas e atualizações.',
    email_placeholder: 'Digite seu e-mail',
    subscribe: 'Inscrever-se',
    all_rights_reserved: 'Todos os direitos reservados.'
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved && translations[saved] ? saved : 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
