import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Navbar
    trips: 'Trips',
    weather: 'Weather',
    tracker: 'Tracker',
    hotels: 'Hotels',
    budgets: 'Budgets',
    logged_in_as: 'Logged in as',
    profile: 'Profile',
    logout: 'Log Out',
    light_mode: 'Light Mode',
    dark_mode: 'Dark Mode',
    globe: 'Globe',
    
    // Tracker Page
    sky_radar: 'Sky Radar',
    live_api: 'Live API',
    simulated_radar: 'Simulated Radar',
    tracked: 'Tracked',
    avg_speed: 'Avg Speed',
    avg_altitude: 'Avg Alt',
    search_placeholder: 'Search flight no. or country...',
    scanning_skies: 'Scanning skies for aircraft...',
    error_connecting: 'Unable to connect to flight server. Retrying...',
    try_again: 'Try again',
    next_update: 'Next update in',
    full_map: 'Full Map',
    show_radar_list: 'Show Radar List',
    en_route: 'EN ROUTE',
    origin: 'Origin',
    dest: 'Dest',
    heading: 'Heading',
    speed: 'Speed',
    altitude: 'Altitude',
    vrate: 'V-Rate',
    legend_title: 'Altitude Legend',
    legend_cruising: 'Cruising (> 30,000 ft)',
    legend_transition: 'Transition (10,000 - 30,000 ft)',
    legend_approach: 'Approach/Takeoff (< 10,000 ft)',
    legend_selected: 'Selected Aircraft',

    // Dashboard / Trips Page
    dashboard_title: 'My Trips Dashboard',
    dashboard_desc: 'Create and manage your customized itineraries.',
    create_new_trip: 'Create New Trip',
    recommended_trips: 'Recommended Pre-planned Trips',
    days_schedule: 'Days Custom Schedule',
    travelers: 'Travelers',
    my_saved_itineraries: 'My Saved Itineraries',
    loading_saved: 'Loading saved itineraries...',
    no_trips: 'No trips created yet',
    get_started: 'Get started by planning your first custom travel itinerary.',
    start_planning: 'Start Planning',
    day: 'day',
    days: 'days',
    budget_label: 'Budget',

    // Profile Page
    profile_title: 'User Profile',
    profile_desc: 'Manage your account settings, preferences, and view your stats.',
    back_to_dashboard: 'Back to Dashboard',
    joined: 'Joined',
    google_account_linked: 'Google Account Linked',
    log_out_session: 'Log Out of Session',
    travel_stats: 'Your Travel Stats',
    trips_planned: 'Trips Planned',
    total_itineraries: 'Total itineraries generated',
    favorites: 'Favorites',
    saved_locations: 'Saved locations & hotels',
    total_estimated_budget: 'Total Estimated Budget',
    total_spent: 'Combined value of planned trips',
    account_details: 'Account Details',
    full_name: 'Full Name',
    email_address: 'Email Address',
    change_password_label: 'Change Password',
    new_password_label: 'New Password',
    confirm_new_password_label: 'Confirm New Password',
    security_checklist: 'Security Checklist',
    travel_preferences_title: 'Travel Preferences',
    preferred_style: 'Preferred Travel Style',
    preferred_currency: 'Preferred Currency',
    email_notifications: 'Email Notifications',
    recommendations_desc: 'Recommendations and trip reminders',
    weekly_digest: 'Weekly Digest',
    curated_news_desc: 'Curated newsletters and travel deals',
    favorite_themes: 'Favorite Travel Themes',
    save_preferences: 'Save Preferences',
    save_changes: 'Save Changes',

    // Travel Styles Options
    style_adventure: 'Adventure & Exploring',
    style_leisure: 'Relaxation & Leisure',
    style_balanced: 'Balanced Mix',
    style_budget: 'Budget Backpacking',
    style_culinary: 'Culinary & Culture'
  },
  es: {
    // Navbar
    trips: 'Viajes',
    weather: 'Clima',
    tracker: 'Rastreador',
    hotels: 'Hoteles',
    budgets: 'Presupuestos',
    logged_in_as: 'Conectado como',
    profile: 'Perfil',
    logout: 'Cerrar Sesión',
    light_mode: 'Modo Claro',
    dark_mode: 'Modo Oscuro',
    globe: 'Globo',
    
    // Tracker Page
    sky_radar: 'Radar del Cielo',
    live_api: 'API en Vivo',
    simulated_radar: 'Radar Simulado',
    tracked: 'Rastreados',
    avg_speed: 'Vel. Promedio',
    avg_altitude: 'Alt. Promedio',
    search_placeholder: 'Buscar vuelo o país...',
    scanning_skies: 'Escaneando los cielos...',
    error_connecting: 'Error al conectar con el servidor de vuelo. Reintentando...',
    try_again: 'Intentar de nuevo',
    next_update: 'Próxima actualización en',
    full_map: 'Mapa Completo',
    show_radar_list: 'Mostrar Lista',
    en_route: 'EN RUTA',
    origin: 'Origen',
    dest: 'Destino',
    heading: 'Rumbo',
    speed: 'Velocidad',
    altitude: 'Altitud',
    vrate: 'Tasa Vertical',
    legend_title: 'Leyenda de Altitud',
    legend_cruising: 'Crucero (> 30,000 ft)',
    legend_transition: 'Transición (10k - 30k ft)',
    legend_approach: 'Despegue/Aterrizaje (< 10k ft)',
    legend_selected: 'Aeronave Seleccionada',

    // Dashboard / Trips Page
    dashboard_title: 'Mi Panel de Viajes',
    dashboard_desc: 'Crea y gestiona tus itinerarios personalizados.',
    create_new_trip: 'Crear Nuevo Viaje',
    recommended_trips: 'Viajes Recomendados Pre-planificados',
    days_schedule: 'Días de Horario Personalizado',
    travelers: 'Viajeros',
    my_saved_itineraries: 'Mis Itinerarios Guardados',
    loading_saved: 'Cargando itinerarios guardados...',
    no_trips: 'Aún no se han creado viajes',
    get_started: 'Comienza planeando tu primer itinerario de viaje personalizado.',
    start_planning: 'Iniciar Planificación',
    day: 'día',
    days: 'días',
    budget_label: 'Presupuesto',

    // Profile Page
    profile_title: 'Perfil de Usuario',
    profile_desc: 'Administra la configuración de tu cuenta, preferencias y estadísticas.',
    back_to_dashboard: 'Volver al Panel',
    joined: 'Registrado',
    google_account_linked: 'Cuenta de Google Vinculada',
    log_out_session: 'Cerrar Sesión',
    travel_stats: 'Estadísticas de Viajes',
    trips_planned: 'Viajes Planificados',
    total_itineraries: 'Itinerarios totales generados',
    favorites: 'Favoritos',
    saved_locations: 'Lugares y hoteles guardados',
    total_estimated_budget: 'Presupuesto Total Estimado',
    total_spent: 'Costo acumulado de viajes',
    account_details: 'Detalles de la Cuenta',
    full_name: 'Nombre Completo',
    email_address: 'Dirección de Correo',
    change_password_label: 'Cambiar Contraseña',
    new_password_label: 'Nueva Contraseña',
    confirm_new_password_label: 'Confirmar Nueva Contraseña',
    security_checklist: 'Lista de Seguridad',
    travel_preferences_title: 'Preferencias de Viaje',
    preferred_style: 'Estilo de Viaje Preferido',
    preferred_currency: 'Moneda Preferida',
    email_notifications: 'Notificaciones de Correo',
    recommendations_desc: 'Recomendaciones y recordatorios',
    weekly_digest: 'Resumen Semanal',
    curated_news_desc: 'Boletines y ofertas de viajes curados',
    favorite_themes: 'Temas de Viaje Favoritos',
    save_preferences: 'Guardar Preferencias',
    save_changes: 'Guardar Cambios',

    // Travel Styles Options
    style_adventure: 'Aventura y Exploración',
    style_leisure: 'Relajación y Ocio',
    style_balanced: 'Mezcla Equilibrada',
    style_budget: 'Mochilero Económico',
    style_culinary: 'Culinaria y Cultura'
  },
  fr: {
    // Navbar
    trips: 'Voyages',
    weather: 'Météo',
    tracker: 'Radar',
    hotels: 'Hôtels',
    budgets: 'Budgets',
    logged_in_as: 'Connecté en tant que',
    profile: 'Profil',
    logout: 'Déconnexion',
    light_mode: 'Mode Clair',
    dark_mode: 'Mode Sombre',
    globe: 'Globe',
    
    // Tracker Page
    sky_radar: 'Radar Aérien',
    live_api: 'API en Direct',
    simulated_radar: 'Radar Simulé',
    tracked: 'Suivis',
    avg_speed: 'Vitesse Moy.',
    avg_altitude: 'Alt. Moyenne',
    search_placeholder: 'Rechercher un vol ou un pays...',
    scanning_skies: 'Scan du ciel en cours...',
    error_connecting: 'Impossible de se connecter au serveur. Re-tentative...',
    try_again: 'Réessayer',
    next_update: 'Mise à jour dans',
    full_map: 'Plein Écran',
    show_radar_list: 'Afficher la Liste',
    en_route: 'EN VOL',
    origin: 'Origine',
    dest: 'Destination',
    heading: 'Cap',
    speed: 'Vitesse',
    altitude: 'Altitude',
    vrate: 'Vitesse Vert.',
    legend_title: 'Légende des Altitudes',
    legend_cruising: 'Croisière (> 30 000 ft)',
    legend_transition: 'Transition (10k - 30k ft)',
    legend_approach: 'Approche/Décollage (< 10k ft)',
    legend_selected: 'Appareil Sélectionné',

    // Dashboard / Trips Page
    dashboard_title: 'Mon Tableau de Bord de Voyages',
    dashboard_desc: 'Créez et gérez vos itinéraires personnalisés.',
    create_new_trip: 'Créer un Nouveau Voyage',
    recommended_trips: 'Voyages Recommandés Pré-planifiés',
    days_schedule: 'Jours de Programme Personnalisé',
    travelers: 'Voyageurs',
    my_saved_itineraries: 'Mes Itinéraires Enregistrés',
    loading_saved: 'Chargement des itinéraires enregistrés...',
    no_trips: 'Aucun voyage créé pour le moment',
    get_started: 'Commencez par planifier votre premier itinéraire de voyage personnalisé.',
    start_planning: 'Commencer la Planification',
    day: 'jour',
    days: 'jours',
    budget_label: 'Budget',

    // Profile Page
    profile_title: 'Profil Utilisateur',
    profile_desc: 'Gérez les paramètres de votre compte, vos préférences et statistiques.',
    back_to_dashboard: 'Retour au Tableau de Bord',
    joined: 'Inscrit',
    google_account_linked: 'Compte Google Associé',
    log_out_session: 'Se Déconnecter de la Session',
    travel_stats: 'Statistiques de Voyage',
    trips_planned: 'Voyages Planifiés',
    total_itineraries: 'Itinéraires totaux générés',
    favorites: 'Favoris',
    saved_locations: 'Lieux & hôtels enregistrés',
    total_estimated_budget: 'Budget Total Estimé',
    total_spent: 'Coût cumulé des voyages',
    account_details: 'Détails du Compte',
    full_name: 'Nom Complet',
    email_address: 'Adresse E-mail',
    change_password_label: 'Changer le Mot de Passe',
    new_password_label: 'Nouveau Mot de Passe',
    confirm_new_password_label: 'Confirmer le Nouveau Mot de Passe',
    security_checklist: 'Liste de Sécurité',
    travel_preferences_title: 'Préférences de Voyage',
    preferred_style: 'Style de Voyage Préféré',
    preferred_currency: 'Devise Préférée',
    email_notifications: 'Notifications par E-mail',
    recommendations_desc: 'Recommandations et rappels',
    weekly_digest: 'Résumé Hebdomadaire',
    curated_news_desc: 'Newsletters et offres de voyages',
    favorite_themes: 'Thèmes de Voyage Favoris',
    save_preferences: 'Enregistrer les Préférences',
    save_changes: 'Enregistrer les Modifications',

    // Travel Styles Options
    style_adventure: 'Aventure & Exploration',
    style_leisure: 'Détente & Loisirs',
    style_balanced: 'Mélange Équilibré',
    style_budget: 'Backpacking Économique',
    style_culinary: 'Culinaire & Culture'
  },
  de: {
    // Navbar
    trips: 'Reisen',
    weather: 'Wetter',
    tracker: 'Flugradar',
    hotels: 'Hotels',
    budgets: 'Budgets',
    logged_in_as: 'Angemeldet als',
    profile: 'Profil',
    logout: 'Abmelden',
    light_mode: 'Heller Modus',
    dark_mode: 'Dunkler Modus',
    globe: 'Globus',
    
    // Tracker Page
    sky_radar: 'Flugradar',
    live_api: 'Live-API',
    simulated_radar: 'Simulierter Radar',
    tracked: 'Verfolgt',
    avg_speed: 'Durchschnittsgeschw.',
    avg_altitude: 'Durchschnittshöhe',
    search_placeholder: 'Suche Flugnr. oder Land...',
    scanning_skies: 'Scanne den Himmel...',
    error_connecting: 'Verbindung zum Server fehlgeschlagen. Erneuter Versuch...',
    try_again: 'Erneut versuchen',
    next_update: 'Nächstes Update in',
    full_map: 'Vollbildkarte',
    show_radar_list: 'Liste anzeigen',
    en_route: 'UNTERWEGS',
    origin: 'Abflug',
    dest: 'Ankunft',
    heading: 'Kurs',
    speed: 'Geschw.',
    altitude: 'Höhe',
    vrate: 'Steigrate',
    legend_title: 'Höhenlegende',
    legend_cruising: 'Reiseflug (> 30.000 ft)',
    legend_transition: 'Übergang (10k - 30k ft)',
    legend_approach: 'Steig-/Sinkflug (< 10k ft)',
    legend_selected: 'Ausgewähltes Flugzeug',

    // Dashboard / Trips Page
    dashboard_title: 'Mein Reise-Dashboard',
    dashboard_desc: 'Erstellen und verwalten Sie Ihre individuellen Reiserouten.',
    create_new_trip: 'Neue Reise erstellen',
    recommended_trips: 'Empfohlene vorgeplante Reisen',
    days_schedule: 'Tage individueller Zeitplan',
    travelers: 'Reisende',
    my_saved_itineraries: 'Meine gespeicherten Reiserouten',
    loading_saved: 'Lade gespeicherte Reiserouten...',
    no_trips: 'Noch keine Reisen erstellt',
    get_started: 'Beginnen Sie mit der Planung Ihrer ersten individuellen Reiseroute.',
    start_planning: 'Planung starten',
    day: 'Tag',
    days: 'Tage',
    budget_label: 'Budget',

    // Profile Page
    profile_title: 'Benutzerprofil',
    profile_desc: 'Verwalten Sie Ihre Kontoeinstellungen, Präferenzen und Statistiken.',
    back_to_dashboard: 'Zurück zum Dashboard',
    joined: 'Mitglied seit',
    google_account_linked: 'Google-Konto verknüpft',
    log_out_session: 'Abmelden',
    travel_stats: 'Reisestatistiken',
    trips_planned: 'Geplante Reisen',
    total_itineraries: 'Gesamte Reiserouten',
    favorites: 'Favoriten',
    saved_locations: 'Gespeicherte Orte & Hotels',
    total_estimated_budget: 'Geschätztes Gesamtbudget',
    total_spent: 'Gesamtwert der geplanten Reisen',
    account_details: 'Kontodetails',
    full_name: 'Vollständiger Name',
    email_address: 'E-Mail-Adresse',
    change_password_label: 'Passwort ändern',
    new_password_label: 'Neues Passwort',
    confirm_new_password_label: 'Neues Passwort bestätigen',
    security_checklist: 'Sicherheitscheckliste',
    travel_preferences_title: 'Reisepräferenzen',
    preferred_style: 'Bevorzugter Reisestil',
    preferred_currency: 'Bevorzugte Währung',
    email_notifications: 'E-Mail-Benachrichtigungen',
    recommendations_desc: 'Empfehlungen und Reiseerinnerungen',
    weekly_digest: 'Wöchentliche Zusammenfassung',
    curated_news_desc: 'Kuratierte Newsletter und Reiseangebote',
    favorite_themes: 'Bevorzugte Reisethemen',
    save_preferences: 'Präferenzen speichern',
    save_changes: 'Änderungen speichern',

    // Travel Styles Options
    style_adventure: 'Abenteuer & Erkunden',
    style_leisure: 'Entspannung & Freizeit',
    style_balanced: 'Ausgewogene Mischung',
    style_budget: 'Günstiges Backpacking',
    style_culinary: 'Kulinarisch & Kultur'
  },
  hi: {
    // Navbar
    trips: 'यात्राएं',
    weather: 'मौसम',
    tracker: 'ट्रैकर',
    hotels: 'होटल',
    budgets: 'बजट',
    logged_in_as: 'लॉग इन किया है',
    profile: 'प्रोफ़ाइल',
    logout: 'लॉग आउट',
    light_mode: 'लाइट मोड',
    dark_mode: 'डार्क मोड',
    globe: 'ग्लोब',
    
    // Tracker Page
    sky_radar: 'आकाश रडार',
    live_api: 'लाइव एपीआई',
    simulated_radar: 'सिम्युलेटेड रडार',
    tracked: 'ट्रैक किया गया',
    avg_speed: 'औसत गति',
    avg_altitude: 'औसत ऊंचाई',
    search_placeholder: 'फ्लाइट नंबर या देश खोजें...',
    scanning_skies: 'आसमान में विमानों की खोज की जा रही है...',
    error_connecting: 'फ्लाइट सर्वर से जुड़ने में असमर्थ...',
    try_again: 'पुनः प्रयास करें',
    next_update: 'अगला अपडेट',
    full_map: 'पूरा नक्शा',
    show_radar_list: 'सूची दिखाएं',
    en_route: 'मार्ग में',
    origin: 'प्रस्थान',
    dest: 'गंतव्य',
    heading: 'दिशा',
    speed: 'गति',
    altitude: 'ऊंचाई',
    vrate: 'वर्टिकल रेट',
    legend_title: 'ऊंचाई का नक्शा',
    legend_cruising: 'क्रूज़िंग (> ३०,००० फीट)',
    legend_transition: 'संक्रमण (१०,००० - ३०,००० फीट)',
    legend_approach: 'टेकऑफ़/लैंडिंग (< १०,००० फीट)',
    legend_selected: 'चयनित विमान',

    // Dashboard / Trips Page
    dashboard_title: 'मेरा यात्रा डैशबोर्ड',
    dashboard_desc: 'अपनी अनुकूलित यात्रा कार्यक्रम बनाएं और प्रबंधित करें।',
    create_new_trip: 'नई यात्रा बनाएं',
    recommended_trips: 'अनुशंसित पूर्व-नियोजित यात्राएं',
    days_schedule: 'दिनों का कस्टम शेड्यूल',
    travelers: 'यात्री',
    my_saved_itineraries: 'मेरे सहेजे गए यात्रा कार्यक्रम',
    loading_saved: 'सहेजे गए यात्रा कार्यक्रमों को लोड किया जा रहा है...',
    no_trips: 'अभी तक कोई यात्रा नहीं बनाई गई है',
    get_started: 'अपने पहले कस्टम यात्रा कार्यक्रम की योजना बनाकर शुरुआत करें।',
    start_planning: 'योजना बनाना शुरू करें',
    day: 'दिन',
    days: 'दिन',
    budget_label: 'बजट',

    // Profile Page
    profile_title: 'उपयोगकर्ता प्रोफ़ाइल',
    profile_desc: 'अपनी खाता सेटिंग, प्राथमिकताएं और आंकड़े प्रबंधित करें।',
    back_to_dashboard: 'डैशबोर्ड पर वापस जाएं',
    joined: 'शामिल हुए',
    google_account_linked: 'गूगल खाता लिंक किया गया',
    log_out_session: 'सत्र से लॉग आउट करें',
    travel_stats: 'आपके यात्रा आंकड़े',
    trips_planned: 'नियोजित यात्राएं',
    total_itineraries: 'उत्पन्न की गई कुल यात्रा कार्यक्रम',
    favorites: 'पसंदीदा',
    saved_locations: 'सहेजे गए स्थान और होटल',
    total_estimated_budget: 'कुल अनुमानित बजट',
    total_spent: 'नियोजित यात्राओं का कुल मूल्य',
    account_details: 'खाता विवरण',
    full_name: 'पूरा नाम',
    email_address: 'ईमेल पता',
    change_password_label: 'पासवर्ड बदलें',
    new_password_label: 'नया पासवर्ड',
    confirm_new_password_label: 'नए पासवर्ड की पुष्टि करें',
    security_checklist: 'सुरक्षा चेकलिस्ट',
    travel_preferences_title: 'यात्रा प्राथमिकताएं',
    preferred_style: 'पसंदीदा यात्रा शैली',
    preferred_currency: 'पसंदीदा मुद्रा',
    email_notifications: 'ईमेल सूचनाएं',
    recommendations_desc: 'सिफारिशें और यात्रा अनुस्मारक',
    weekly_digest: 'साप-साप्ताहिक सारांश',
    curated_news_desc: 'क्यूरेटेड न्यूजलेटर और यात्रा सौदे',
    favorite_themes: 'पसंदीदा यात्रा थीम',
    save_preferences: 'प्राथमिकताएं सहेजें',
    save_changes: 'परिवर्तन सहेजें',

    // Travel Styles Options
    style_adventure: 'साहसिक और अन्वेषण',
    style_leisure: 'विश्राम और आराम',
    style_balanced: 'संतुलित मिश्रण',
    style_budget: 'बजट बैकपैकिंग',
    style_culinary: 'पाक कला और संस्कृति'
  },
  ar: {
    // Navbar
    trips: 'رحلاتي',
    weather: 'الطقس',
    tracker: 'الرادار',
    hotels: 'الفنادق',
    budgets: 'الميزانية',
    logged_in_as: 'مسجل كـ',
    profile: 'الملف الشخصي',
    logout: 'تسجيل الخروج',
    light_mode: 'وضع فاتح',
    dark_mode: 'وضع داكن',
    globe: 'الكرة الأرضية',
    
    // Tracker Page
    sky_radar: 'رادار السماء',
    live_api: 'بث مباشر',
    simulated_radar: 'رادار محاكي',
    tracked: 'المتتبع',
    avg_speed: 'متوسط السرعة',
    avg_altitude: 'متوسط الارتفاع',
    search_placeholder: 'بحث برقم الرحلة أو البلد...',
    scanning_skies: 'جاري مسح السماء بحثاً عن طائرات...',
    error_connecting: 'تعذر الاتصال بخادم الرحلة...',
    try_again: 'أعد المحاولة',
    next_update: 'التحديث القادم في',
    full_map: 'الخريطة الكاملة',
    show_radar_list: 'عرض القائمة',
    en_route: 'في الطريق',
    origin: 'المنشأ',
    dest: 'الوجهة',
    heading: 'الاتجاه',
    speed: 'السرعة',
    altitude: 'الارتفاع',
    vrate: 'المعدل العمودي',
    legend_title: 'دليل الارتفاع',
    legend_cruising: 'طيران مستقر (> ٣٠ ألف قدم)',
    legend_transition: 'ارتفاع انتقالي (١٠-٣٠ ألف قدم)',
    legend_approach: 'إقلاع وهبوط (< ١٠ آلاف قدم)',
    legend_selected: 'الطائرة المحددة',

    // Dashboard / Trips Page
    dashboard_title: 'لوحة رحلاتي',
    dashboard_desc: 'إنشاء وإدارة مساراتك المخصصة.',
    create_new_trip: 'إنشاء رحلة جديدة',
    recommended_trips: 'رحلات ما قبل التخطيط الموصى بها',
    days_schedule: 'أيام جدول مخصص',
    travelers: 'مسافرين',
    my_saved_itineraries: 'مساراتي المحفوظة',
    loading_saved: 'جاري تحميل مساراتك المحفوظة...',
    no_trips: 'لم يتم إنشاء أي رحلات بعد',
    get_started: 'ابدأ بالتخطيط لأول مسار سفر مخصص لك.',
    start_planning: 'ابدأ التخطيط',
    day: 'يوم',
    days: 'أيام',
    budget_label: 'الميزانية',

    // Profile Page
    profile_title: 'ملف المستخدم',
    profile_desc: 'إدارة إعدادات حسابك، وتفضيلاتك، وعرض إحصائياتك.',
    back_to_dashboard: 'العودة إلى لوحة القيادة',
    joined: 'انضم في',
    google_account_linked: 'حساب Google مرتبط',
    log_out_session: 'تسجيل الخروج من الجلسة',
    travel_stats: 'إحصاءات سفرك',
    trips_planned: 'الرحلات المخططة',
    total_itineraries: 'إجمالي مسارات الرحلات المنشأة',
    favorites: 'المفضلة',
    saved_locations: 'المواقع والفنادق المحفوظة',
    total_estimated_budget: 'إجمالي الميزانية التقديرية',
    total_spent: 'القيمة الإجمالية للرحلات المخططة',
    account_details: 'تفاصيل الحساب',
    full_name: 'الاسم الكامل',
    email_address: 'عنوان البريد الإلكتروني',
    change_password_label: 'تغيير كلمة المرور',
    new_password_label: 'كلمة المرور الجديدة',
    confirm_new_password_label: 'تأكيد كلمة المرور الجديدة',
    security_checklist: 'قائمة مرجعية للأمان',
    travel_preferences_title: 'تفضيلات السفر',
    preferred_style: 'أسلوب السفر المفضل',
    preferred_currency: 'العملة المفضلة',
    email_notifications: 'إشعارات البريد الإلكتروني',
    recommendations_desc: 'التوصيات وتذكيرات الرحلات',
    weekly_digest: 'الموجز الأسبوعي',
    curated_news_desc: 'النشرات الإخبارية وعروض السفر المنسقة',
    favorite_themes: 'مواضيع السفر المفضلة',
    save_preferences: 'حفظ التفضيلات',
    save_changes: 'حفظ التغييرات',

    // Travel Styles Options
    style_adventure: 'مغامرة واستكشاف',
    style_leisure: 'الاسترخاء والترفيه',
    style_balanced: 'مزيج متوازن',
    style_budget: 'السفر بميزانية محدودة',
    style_culinary: 'المطبخ والثقافة'
  },
  pt: {
    // Navbar
    trips: 'Viagens',
    weather: 'Clima',
    tracker: 'Rastreador',
    hotels: 'Hotéis',
    budgets: 'Orçamentos',
    logged_in_as: 'Sessão como',
    profile: 'Perfil',
    logout: 'Sair',
    light_mode: 'Modo Claro',
    dark_mode: 'Modo Escuro',
    globe: 'Globo',
    
    // Tracker Page
    sky_radar: 'Radar Aéreo',
    live_api: 'API em Tempo Real',
    simulated_radar: 'Radar Simulado',
    tracked: 'Rastreados',
    avg_speed: 'Vel. Média',
    avg_altitude: 'Alt. Média',
    search_placeholder: 'Buscar voo ou país...',
    scanning_skies: 'Rastreando aviões nos céus...',
    error_connecting: 'Não foi possível conectar ao servidor...',
    try_again: 'Tentar novamente',
    next_update: 'Próxima atualização em',
    full_map: 'Mapa Completo',
    show_radar_list: 'Mostrar Lista',
    en_route: 'EM ROTA',
    origin: 'Origem',
    dest: 'Destino',
    heading: 'Rumo',
    speed: 'Velocidade',
    altitude: 'Altitude',
    vrate: 'Taxa Vertical',
    legend_title: 'Legenda de Altitude',
    legend_cruising: 'Cruzeiro (> 30.000 ft)',
    legend_transition: 'Transição (10k - 30k ft)',
    legend_approach: 'Decolagem/Pouso (< 10k ft)',
    legend_selected: 'Aeronave Selecionada',

    // Dashboard / Trips Page
    dashboard_title: 'Meu Painel de Viagens',
    dashboard_desc: 'Crie e gerencie seus roteiros personalizados.',
    create_new_trip: 'Criar Nova Viagem',
    recommended_trips: 'Viagens Recomendadas Pré-planejadas',
    days_schedule: 'Dias de Programação Personalizada',
    travelers: 'Viajantes',
    my_saved_itineraries: 'Meus Roteiros Salvos',
    loading_saved: 'Carregando roteiros salvos...',
    no_trips: 'Nenhuma viagem criada ainda',
    get_started: 'Comece planejando seu primeiro roteiro de viagem personalizado.',
    start_planning: 'Começar Planejamento',
    day: 'dia',
    days: 'dias',
    budget_label: 'Orçamento',

    // Profile Page
    profile_title: 'Perfil do Usuário',
    profile_desc: 'Gerencie as configurações da sua conta, preferências e veja suas estatísticas.',
    back_to_dashboard: 'Voltar ao Painel',
    joined: 'Registrado em',
    google_account_linked: 'Conta do Google Vinculada',
    log_out_session: 'Sair da Sessão',
    travel_stats: 'Estatísticas de Viagem',
    trips_planned: 'Viagens Planejadas',
    total_itineraries: 'Roteiros totais gerados',
    favorites: 'Favoritos',
    saved_locations: 'Locais e hotéis salvos',
    total_estimated_budget: 'Orçamento Total Estimado',
    total_spent: 'Custo acumulado das viagens',
    account_details: 'Detalhes da Conta',
    full_name: 'Nome Completo',
    email_address: 'Endereço de E-mail',
    change_password_label: 'Alterar Senha',
    new_password_label: 'Nova Senha',
    confirm_new_password_label: 'Confirmar Nova Senha',
    security_checklist: 'Lista de Segurança',
    travel_preferences_title: 'Preferências de Viagem',
    preferred_style: 'Estilo de Viagem Preferido',
    preferred_currency: 'Moeda Preferida',
    email_notifications: 'Notificações por E-mail',
    recommendations_desc: 'Recomendações e lembretes de viagem',
    weekly_digest: 'Resumo Semanal',
    curated_news_desc: 'Newsletters e ofertas de viagens',
    favorite_themes: 'Temas de Viagem Favoritos',
    save_preferences: 'Salvar Preferências',
    save_changes: 'Salvar Alterações',

    // Travel Styles Options
    style_adventure: 'Aventura e Exploração',
    style_leisure: 'Relaxamento e Lazer',
    style_balanced: 'Mistura Equilibrada',
    style_budget: 'Mochilão Econômico',
    style_culinary: 'Culinária e Cultura'
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved && translations[saved] ? saved : 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
